<a href="https://colab.research.google.com/github/acanavire/CD_IA_test/blob/main/Notebooks/2_An%C3%A1lisis_Exploratorio_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ciencia de Datos e Inteligencia Artificial**
# **3. Análisis Exploratorio de Datos**

## 🎯 Manipulación de datos

---
## 🥇 Pandas  test
---

![image.png]()

**Pandas**

es una librería de Python especializada en la manipulación y el análisis de datos. Ofrece estructuras de datos y operaciones para manipular los datos, como tablas numéricas y series temporales.

**Principales características**

- **Colección de estructuras de datos y funciones** que facilitan el trabajo con datos estructurados.

- Nombre derivado de  "**Pan**el **Da**ta **S**ystem" (término econométrico para datasets multidimensionales).

- Construído **en base a Numpy**, inicialmente por Wes McKinney.
    
- Combina la alta performance de las **operaciones sobre arrays de NumPy con la flexibilidad en la manipulación de datos** de un hoja de cálculo o una base de datos relacional.

- Provee **funcionalidades de indexación avanzadas** para facilitar la manipulación, agregación y selección de partes de un conjunto de datos.

- Provee **operaciones de agrupación por columnas, filtros y sumarizaciones**.

- Estas características hacen de Pandas una librería **indispensable para las tareas de limpieza y preprocesamiento de datos**.

Para cargar el paquete Pandas y comenzar a trabajar con él, importar el paquete. El alias acordado por la comunidad para Pandas es `pd`, por lo que cargar Pandas como `pd` se asume como una práctica estándar para toda la documentación de Pandas.

In [ ]:
# Convención de importación para Pandas.
import pandas as pd

### Estructuras de datos
---
Para comenzar a usar Pandas, es importante familiarizarse con sus dos estructuras de datos principales:

* Series
* DataFrame

Cuando trabajas con datos tabulares, como datos almacenados en hojas de cálculo o bases de datos, Pandas es la herramienta adecuada para ti principalmente porque estás estructuras, objetos, presentan métodos y atributos que permiten por ejemplo:

* Leer un conjunto de datos.
* Limpiar un conjunto de datos.
* Selecionar, ordenar y remodelar la estructura de un conjunto de datos.
* Aplicar operaciones aritméticas, de texto, de series temporales en un conjunto de datos.
* Visualizar un conjunto de datos.

![estructura de datos.png]()

#### Series
---
- Es un objeto similar a un **vector unidimensional**.
- Colección de valores que mantiene un orden. Los valores pueden ser de cualquier tipo de datos, como números enteros, cadenas, objetos de Python, etc.
- Esta formado por una colección de valores y una colección de etiquetas de estos valores denominado **índice** (index).



![image.png]()

La serie más simple se forma a partir de una lista de datos.

Si necesitas reforzar sobre las estructuras de datos en Python, mirar la notebook **Fundamentos** de este curso o click en [Estructura de datos de la documentación oficial de Python](https://docs.python.org/es/3/tutorial/datastructures.html).

In [ ]:
# Pasar como argumento la lista = [4, 17, -51, 3]
s = pd.Series([4, 17, -51, 3])
s

0     4
1    17
2   -51
3     3
dtype: int64

Como no especificamos un índice para los datos, se crea uno predeterminado que consta de los números enteros del 0 al N - 1 (donde N es la longitud de los datos). Para el ejemplo la serie tiene una colección de N=4 valores y el indice es una colección de enteros de 0 a 3.

Para acceder a la colección de valores y al indice considerar los atributos de la serie `value` e `index` respectivamente:

In [ ]:
# Colección de valores
s.values

array([  4,  17, -51,   3])

In [ ]:
# Colección de etiquetas. Indice
s.index

RangeIndex(start=0, stop=4, step=1)

📝 **Ejercicio**

Crea tu primera Serie desde la lista [0,'A','B', 4, 2] . Llamar a la variable `tiposdedatos_s`.

```
tiposdedatos_s = ...
```

In [ ]:
# Ejercicio

**Haz doble click para ver la respuesta**

<!--
# Crear serie
tiposdedatos_s = pd.Series( [0,'A','B', 4, 2])

# Mostrar
tiposdedatos_s
 -->

A menudo será deseable crear una serie con un índice que identifique cada punto de datos:

In [ ]:
# Crear serie
s = pd.Series ([4, 17, -51, 3], index=['d', 'b', 'a', 'c'])
s

d     4
b    17
a   -51
c     3
dtype: int64

In [ ]:
# Acceder al indice del objeto s
s.index

Index(['d', 'b', 'a', 'c'], dtype='object')

Puedes utilizar valores en el índice para seleccionar valores individuales o un conjunto de valores de la serie

In [ ]:
# Seleccionar el elemento asociado al valor del indice 'a'
s['a']

-51

In [ ]:
# Seleccionar el elemento asociado al valor del indice ['c', 'a', 'd']
s[['c', 'a', 'd']]

c     3
a   -51
d     4
dtype: int64

In [ ]:
# Serie original
print('Serie original:\n', s)

# Modificar el valor asociado al valor del indice 'd'
s['d'] = 6

# Serie modificada
print('\nSerie modificada:\n', s)

Serie original:
 d     4
b    17
a   -51
c     3
dtype: int64

Serie modificada:
 d     6
b    17
a   -51
c     3
dtype: int64

Las operaciones de array de NumPy, también se aplican en serie, como el filtrado con operadores relacional, la multiplicación por escalar o la aplicación de funciones matemáticas, que preservan el vínculo índice-valor:

In [ ]:
# Serie s
s

d     6
b    17
a   -51
c     3
dtype: int64

In [ ]:
# Filtrar los valores mayores a 0
s[s > 0]

d     6
b    17
c     3
dtype: int64

In [ ]:
# Multiplicar por escalar 2
s * 2

d     12
b     34
a   -102
c      6
dtype: int64

In [ ]:
# Sumar todos los valores
s.sum()

-25

In [ ]:
# Importar librería de Numpy para usar sus funciones definidas
import numpy as np

# Función exponencial
np.exp(s)

d    4.034288e+02
b    2.415495e+07
a    7.095474e-23
c    2.008554e+01
dtype: float64

Si tiene datos contenidos en un diccionario de Python, puede crear una serie a partir de ellos pasando el diccionario:

In [ ]:
# Diccionario en Python formado por datos de superficies de algunas provincias de Argentina.
# Por cada nombre de provincia un valor de superficie [km²] asociado.
superficie_dict = {'Buenos Aires': 305907.4, 'Córdoba': 164707.8, 'Salta': 155340.5,'Tucumán': 22592.1,'La Rioja': 91493.7}

# Serie desde dict
superficie_s = pd.Series(superficie_dict)

# Serie
superficie_s

Buenos Aires    305907.4
Córdoba         164707.8
Salta           155340.5
Tucumán          22592.1
La Rioja         91493.7
dtype: float64

Cuando solo se pasa un diccionario, el índice de la serie resultante tendrá las claves del diccionario en el orden generado.

In [ ]:
# Crear serie desde un diccionario e indice

# Crear lista de provincias
provincias = ['Buenos Aires', 'Córdoba', 'Salta', 'Misiones']

# Crear serie
superficie_s2 = pd.Series(superficie_s, index=provincias)

# Mostrar
superficie_s2

Buenos Aires    305907.4
Córdoba         164707.8
Salta           155340.5
Misiones             NaN
dtype: float64

En este caso, se colocaron 3 valores encontrados en superficie_s en las ubicaciones correspondientes, pero como no se encontró ningún valor para 'Misiones', aparece como `NaN` (Not a Number), lo que en Pandas se considera para marcar valores faltantes o NA.

Usaremos los términos "faltante" o "NA" para referirnos a los datos faltantes. Las funciones `isnull` y `notnull` en Pandas se usan para detectar datos faltantes:

In [ ]:
# Usar la función isnull de Pandas. Se pasa como argumento una serie.
# Se evalúa si el dato en DataFrame es dato faltante.
pd.isnull(superficie_s2)

Buenos Aires    False
Córdoba         False
Salta           False
Misiones         True
dtype: bool

In [ ]:
# Usar la función notnull de Pandas. Se pasa como argumento una serie.
# Se evalúa si el dato en DataFrame no es dato faltante.
pd.notnull(superficie_s2)

Buenos Aires     True
Córdoba          True
Salta            True
Misiones        False
dtype: bool

La serie también tiene estos métodos de instancia.

In [ ]:
# Función isnull de la serie
superficie_s2.isnull()

Buenos Aires    False
Córdoba         False
Salta           False
Misiones         True
dtype: bool

Más adelante se analizará con más detalle cómo trabajar con datos faltantes.

#### DataFrame
---
- Representa una estructura de datos tabular, similar a una hoja de cálculo, que contiene una colección ordenada de columnas, cada una de las cuales puede ser de un tipo de valor diferente (numérico, cadena, booleano, etc.).
- El `DataFrame` tiene índices de columnas y filas.
- Cada columna de un `DataFrame` es una `Serie`.



![image.png]()

Vamos a construir dos instancias de Series:

- `superficie_s`, a partir de un diccionario. Retomamos el ejemplo anterior.

- `población_s`, a partir de dos listas

Luego construimos el DataFrame `provincia_df` a partir de las dos Series.

In [ ]:
# Diccionario en python formado por datos de superficies de algunas provincias de Argentina.
# Por cada nombre de provincia un valor de superficie [km²] asociado.
superficie_dict = {'Buenos Aires': 305907.4, 'Córdoba': 164707.8, 'Salta': 155340.5,'Tucumán': 22592.1,'La Rioja': 91493.7}

# Serie desde dict y le agregamos el nombre
superficie_s = pd.Series(superficie_dict, name = 'superficie')

# Serie
superficie_s

Buenos Aires    305907.4
Córdoba         164707.8
Salta           155340.5
Tucumán          22592.1
La Rioja         91493.7
Name: superficie, dtype: float64

In [ ]:
# Diccionario en python formado por datos de provincias de algunas provincias de Argentina.
# Por cada nombre de provincia un valor de población [km²] asociado.

# Crear lista 1
provincia_lista = ['Buenos Aires','Salta','Córdoba', 'Tucumán', 'La Rioja']

# Crear lista 2
provincia_pop = [17541141, 1424397, 3760450, 1694656, 393531]

# Serie de provincias desde dos listas
poblacion_s = pd.Series(provincia_pop, index= provincia_lista, name= 'poblacion')

# Mostrar Serie con el nombre poblacion
poblacion_s

Buenos Aires    17541141
Salta            1424397
Córdoba          3760450
Tucumán          1694656
La Rioja          393531
Name: poblacion, dtype: int64

In [ ]:
# Mirar atributos de Series
print('Colección de valores:',poblacion_s.values)
print('Colección de etiquetas (indice):',poblacion_s.index)

Colección de valores: [17541141  1424397  3760450  1694656   393531]
Colección de etiquetas (indice): Index(['Buenos Aires', 'Salta', 'Córdoba', 'Tucumán', 'La Rioja'], dtype='object')

Para crear un DataFrame desde un diccionario, tener en cuenta que las claves son las etiquetas de las columnas y los valores son los valores de las colecciones asociadas. Para el ejemplo son los valores de las series creadas previamente.

In [ ]:
# Crear Dataframe
provincia_df = pd.DataFrame( {'Población':poblacion_s, 'Superficie(km2)':superficie_s}  )

In [ ]:
# Mostrar
provincia_df

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
La Rioja         393531          91493.7
Salta           1424397         155340.5
Tucumán         1694656          22592.1

In [ ]:
# Si quisieramos crear desde listas  pero ojo con el indice
# provincia_df2 = pd.DataFrame( {'Población': [17541141, 1424397, 3760450, 1694656, 393531], 'Superficie(km2)':[305907.4,164707.8,91493.7,155340.5, 22592.1]}  )

📝 **Ejercicio**

Crea tu primer DataFrame desde un diccionario. Llamar a la variable `estudiantes_df`. Utilizar el siguiente código:


```
# Importar librería numpy para llamar a random
import numpy as np

# Diccionario est_d

est_d = {
  'Nombre': ['Lucas','Marcela','Fede','Sol'],
  'Edad': np.random.random_integers(18,50,4)
}
```

In [ ]:
# Ejercicio

**Haz doble click para ver la respuesta**
<!--
# Importar librería numpy para llamar a random
import numpy as np

# Diccionario est_d

est_d = {
  'Nombre': ['Lucas','Marcela','Fede','Sol'],
  'Edad': np.random.random_integers(18,50,4)
}

# Crear DataFrame
estudiantes_df = pd.DataFrame(est_d)

# Mostrar
estudiantes_df
-->

El índice del DataFrame resultante se crea en base a los indices de las series (que son los nombres de las provincias), y las columnas se organizan en el orden en como se asigno las claves del diccionario. Si no se especificará, se generará un indice automáticamente como en el caso de Series.

Las columnas del DataFrame resultante tienen diferentes tipos de datos:

In [ ]:
# dtypes
provincia_df.dtypes

Población            int64
Superficie(km2)    float64
dtype: object

🔎 **Nota**

En su mayor parte, Pandas utiliza arrays y tipos de datos de NumPy para las series o las columnas individuales de un DataFrame. NumPy ofrece compatibilidad con float, int, bool, timedelta64[ns] y datetime64[ns]. Para más información click en [dtypes en documentación oficial de Pandas](https://Pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes) (inglés).

**Atributos y datos subyacentes de DataFrame**

In [ ]:
# Ver tupla que representa la dimensionalidad del DataFrame.
# (cantidad de filas, cantidad de columnas)
provincia_df.shape

(5, 2)

In [ ]:
# Ver índice (etiquetas de fila) del DataFrame.
provincia_df.index

Index(['Buenos Aires', 'Córdoba', 'La Rioja', 'Salta', 'Tucumán'], dtype='object')

In [ ]:
# Ver las etiquetas de las columnas del DataFrame.
provincia_df.columns

Index(['Población', 'Superficie(km2)'], dtype='object')

In [ ]:
# Ver los valores del Dataframe. Devuelve una representación Numpy del DataFrame.
provincia_df.values

array([[17541141. ,   305907.4],
       [ 3760450. ,   164707.8],
       [  393531. ,    91493.7],
       [ 1424397. ,   155340.5],
       [ 1694656. ,    22592.1]])

### Indexación y selección de datos
---

Cada columna en un `DataFrame` es una `Serie`. Para acceder a una columna :

In [ ]:
# Acceder a los datos de la columna cuya etiqueta es 'Población'
provincia_df['Población']

Buenos Aires    17541141
Córdoba          3760450
La Rioja          393531
Salta            1424397
Tucumán          1694656
Name: Población, dtype: int64

In [ ]:
# Como serie se puede llamar a sus atributos y métodos
print('Valores de la serie' , provincia_df['Población'].values)
print('Suma de los valores de la serie' , provincia_df['Población'].sum())

Valores de la serie [17541141  3760450   393531  1424397  1694656]
Suma de los valores de la serie 24814175

In [ ]:
# Otra forma
# provincia_df.Población

In [ ]:
# Acceder al dato de la columna cuya etiqueta es 'Población' y fila cuya etiqueta es 'Buenos Aires' (ver indice del DataFrame)
provincia_df['Población']['Buenos Aires']

17541141

In [ ]:
# Otra forma
provincia_df.Población['Buenos Aires']

17541141

Las filas también se pueden recuperar por posición o nombre mediante un par de métodos. Usando las posiciones y el método `iloc` o las etiquetas y el método `loc`.

`iloc` se basa principalmente en la posición de números enteros pero también se puede utilizar con un array booleano.

**Indexación de sola las filas**

In [ ]:
# Número entero - escalar
# Fila en la posicion 0
provincia_df.iloc[0]

Población          17541141.0
Superficie(km2)      305907.4
Name: Buenos Aires, dtype: float64

In [ ]:
# Lista de números enteros [0]
provincia_df.iloc[[0]]

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4

In [ ]:
# Lista de números enteros [0,2] , filas de la posición 0 y posición 3

provincia_df.iloc[[0,3]]

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Salta           1424397         155340.5

In [ ]:
# Con un objeto de corte (slice)
#  [ini:fin:pasos]
provincia_df.iloc[:3:]

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
La Rioja         393531          91493.7

In [ ]:
# Con una máscara booleana de la misma longitud que el índice. En este caso indice es para las 5 filas
provincia_df.iloc[[True, False, False, False, False]]

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4

**Indexación por fila y columna**

Puede combinar los tipos de indexadores para el índice y las columnas.

In [ ]:
# Datos de la fila en posición 0 y columna en posición 1
provincia_df.iloc[0 , 1]

305907.4

In [ ]:
# Datos de las filas en posición 0 y 2, columna en posición 1
provincia_df.iloc[[0,2] , 1]

Buenos Aires    305907.4
La Rioja         91493.7
Name: Superficie(km2), dtype: float64

In [ ]:
# Con objeto de corte filas y columnas [ini:fin:pasos , ini:fin:pasos]
provincia_df.iloc[:3, :1]

              Población
Buenos Aires   17541141
Córdoba         3760450
La Rioja         393531

`loc` permite el acceso a un grupo de filas y columnas por etiqueta(s) o un array booleano.

In [ ]:
# Ver df
provincia_df

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
La Rioja         393531          91493.7
Salta           1424397         155340.5
Tucumán         1694656          22592.1

In [ ]:
# Etiqueta de fila (indice)
provincia_df.loc['Salta']

Población          1424397.0
Superficie(km2)     155340.5
Name: Salta, dtype: float64

In [ ]:
# Lista de etiquetas de filas
provincia_df.loc[['Salta','Buenos Aires']]

              Población  Superficie(km2)
Salta           1424397         155340.5
Buenos Aires   17541141         305907.4

In [ ]:
# Etiqueta de fila y columna [ etiqueta fila (indice) , etiqueta columna ]
provincia_df.loc['Salta' ,'Población']

1424397

In [ ]:
# Por lista de etiquetas
provincia_df.loc[['Salta','Buenos Aires'], ['Población']]

              Población
Salta           1424397
Buenos Aires   17541141

In [ ]:
# Por objeto de corte
provincia_df.loc[:'Salta':, :'Población']

              Población
Buenos Aires   17541141
Córdoba         3760450
La Rioja         393531
Salta           1424397

In [ ]:
# Lista booleana con la misma longitud que el eje de filas o columnas
provincia_df.loc[[True, False,False,False,False],[True,False]]

              Población
Buenos Aires   17541141

* La principal diferencia que existe entre loc e iloc es que en loc se usan las etiquetas (los nombres asignados tanto a las filas como a las columnas) mientras que en iloc se usan las posiciones de los elementos (la posición en la fila o la columna, comenzado a contar en 0).

Podemos indexar un DataFrame usando loc y máscaras booleanas

In [ ]:
# Filtro por operador relacional. 'Superficie(km2)' > 148008
provincia_df['Superficie(km2)'] > 148008

Buenos Aires     True
Córdoba          True
La Rioja        False
Salta            True
Tucumán         False
Name: Superficie(km2), dtype: bool

In [ ]:
# Por máscara
provincia_df.loc[provincia_df['Superficie(km2)'] > 148008, ['Población', 'Superficie(km2)']]

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
Salta           1424397         155340.5

In [ ]:
provincia_df.loc[provincia_df['Superficie(km2)'] > 148008, ['Población']]

              Población
Buenos Aires   17541141
Córdoba         3760450
Salta           1424397

📝 **Ejercicio**

Para el DataFrame `provincia_df`, seleccionar las filas cuyos valores de la  columna 'Población' sea mayor o igual a 3 millones (3000000) .

In [ ]:
# Ejercicio

**Haz doble click para ver la respuesta**

<!--
provincia_df.loc[provincia_df['Población'] > 3000000]
-->

Si se desea guardar los datos filtrados del dataframe se puede asignar el resultado del filtrado a una variable

In [ ]:
# Nuevo DataFrame
provincia_cota_df = provincia_df.loc[provincia_df['Superficie(km2)'] > 148008, ['Población']]

# Mostrar
provincia_cota_df

              Población
Buenos Aires   17541141
Córdoba         3760450
Salta           1424397

Otros métodos para la selección de valores que devuelve un subconjunto de los datos son `where`, `mask`, y `query`.

In [ ]:
# where() para reemplazar valores donde la condición sea Falso.
# provincia_df['Superficie(km2)'] > 148008 si es falso los valores serán 0
provincia_filtro_df1 = provincia_df.where(provincia_df['Superficie(km2)'] > 148008, 0 )

# Mostrar
provincia_filtro_df1

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
La Rioja              0              0.0
Salta           1424397         155340.5
Tucumán               0              0.0

In [ ]:
# mask reemplaza los valores donde la condición sea Verdadera.
# provincia_df['Superficie(km2)'] > 148008 si es falso los valores serán 0
provincia_filtro_df2 = provincia_df.mask(provincia_df['Superficie(km2)'] > 148008, 0 )

# Mostrar
provincia_filtro_df2

              Población  Superficie(km2)
Buenos Aires          0              0.0
Córdoba               0              0.0
La Rioja         393531          91493.7
Salta                 0              0.0
Tucumán         1694656          22592.1

In [ ]:
# query para consultar las columnas de un DataFrame con una expresión booleana.
provincia_df.query('`Superficie(km2)` > 148008') # es igual a provincia_df[provincia_df['Superficie(km2)']> 148008]

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
Salta           1424397         155340.5

### Funciones aritméticas y mapeo con Pandas
---

In [ ]:
# Ver DataFrame
provincia_df

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
La Rioja         393531          91493.7
Salta           1424397         155340.5
Tucumán         1694656          22592.1

Operanciones aritméticas

In [ ]:
# Suma por escalar
provincia_df['Superficie(km2)'] + 10

Buenos Aires    305917.4
Córdoba         164717.8
La Rioja         91503.7
Salta           155350.5
Tucumán          22602.1
Name: Superficie(km2), dtype: float64

In [ ]:
# Dividir los valores de la columna ' Población' por la columna 'Superficie(km2)'
provincia_df['Población'] / provincia_df['Superficie(km2)']

Buenos Aires    57.341343
Córdoba         22.831038
La Rioja         4.301181
Salta            9.169515
Tucumán         75.010999
dtype: float64

Funciones aritméticas

In [ ]:
# Suma de los valores sobre el eje solicitado. Por defecto se aplica sobre las filas.
provincia_df.sum(axis=0)

Población          24814175.0
Superficie(km2)      740041.5
dtype: float64

En Pandas:

* axis=0 significa a lo largo de "índices". Es una operación por filas.
* axis=1 significa a lo largo de "columnas". Es una operación por columnas.

In [ ]:
# Media de los valores sobre el eje solicitado. Por defecto se aplica sobre las filas.
provincia_df.mean()

Población          4962835.0
Superficie(km2)     148008.3
dtype: float64

In [ ]:
# Combinar operaciones.
# Por ejemplo estandarización (representar los datos con una media cero y una desviación estándar de 1), de forma muy concisa:
(provincia_df - provincia_df.mean()) / provincia_df.std()

              Población  Superficie(km2)
Buenos Aires   1.762440         1.502305
Córdoba       -0.168475         0.158885
La Rioja      -0.640239        -0.537699
Salta         -0.495797         0.069761
Tucumán       -0.457929        -1.193252

`map` aplica una función a un DataFrame elemento por elemento.
Este método aplica una función que acepta y devuelve un escalar a cada elemento de un DataFrame.

Podemos hacerlo utilizando funciones "lambda". Se utilizan para crear funciones anónimas. La expresión

```
lambda argumento(s) : expresion
```
Genera un objeto de función. El objeto sin nombre se comporta como un objeto de función definido con:

```
def <lambda>(parametros):
    return expresion
```
Para más información sobre `lambda`, click en [expresiones lambda en documentación oficial](https://docs.python.org/3/reference/expressions.html#lambda)

In [ ]:
# con funciones lambda.
provincia_df.map(lambda x: round(x,2))

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
La Rioja         393531          91493.7
Salta           1424397         155340.5
Tucumán         1694656          22592.1

In [ ]:
# También es posible utilizar el mapa con funciones que no son funciones lambda:
provincia_df.map(round, ndigits=1)

              Población  Superficie(km2)
Buenos Aires   17541141         305907.4
Córdoba         3760450         164707.8
La Rioja         393531          91493.7
Salta           1424397         155340.5
Tucumán         1694656          22592.1

 `apply`es una función a lo largo de un eje del DataFrame.

Los objetos que se pasan a la función son objetos Series cuyo índice es el índice del DataFrame (axis=0) o las columnas del DataFrame (axis=1).

Para más información, click en [apply en documento oficial](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html)

In [ ]:
# Numpy
import numpy as np

# Aplicar suma por eje fila, axis = 0.
provincia_df.apply(np.sum, axis=0)

Población          24814175.0
Superficie(km2)      740041.5
dtype: float64

In [ ]:
# Aplicar suma por eje fila, axis = 1.
provincia_df.apply(np.sum, axis=1)

Buenos Aires    17847048.4
Córdoba          3925157.8
La Rioja          485024.7
Salta            1579737.5
Tucumán          1717248.1
dtype: float64

In [ ]:
provincia_df['Superficie(km2)'].apply(round,ndigits=1)

Buenos Aires    305907.4
Córdoba         164707.8
La Rioja         91493.7
Salta           155340.5
Tucumán          22592.1
Name: Superficie(km2), dtype: float64

### ✍ Recordatorio

* Importar el paquete, también conocido como `import pandas as pd`

* Una tabla de datos se almacena como un `DataFrame` de pandas

* Cada columna de un `DataFrame` es una `Series`

* Puedes hacer operaciones sobre los datos aplicando un método a un `DataFrame` o una `Series`

### Ejercicio

Crea una Serie a partir de una lista de 4 nombres y asigna un indice personalizado. Tener en cuenta lo siguiente:
* La serie se guarda en la variable 'nombre_s' .
* El indice personalizado se corresponde a ['a','k','l','c]]

In [ ]:
nombre_s=pd.Series(['Lucía','Sandra','Lucas','Marcos'], index=['a','k','l','c'])

NameError: name 'pd' is not defined

En base a la serie anterior, acceder al nombre que se corresponde al indice 'k'. Imprimir en pantalla

In [ ]:
print("Valor en índice 'c':", serie["c"])

---
## 🥇 Manipulación de datos
---

Python se ha convertido en un lenguaje muy apreciado para la manipulación de textos y archivos debido a su sintaxis sencilla para interactuar con archivos, estructuras de datos intuitivas y funciones prácticas para procesar los datos.

A continuación exploraremos e integraremos tecnologías con Python para responder:

* Importar y exportar conjuntos de datos.
* Ordenar los conjuntos de datos y remodelar su estructura en un formato adecuado para el análisis.

###  ¿Cómo leo y escribo datos tabulares?
---
Pandas admite la integración con muchos formatos de archivos o fuentes de datos de forma predeterminada (csv, excel, sql, json,  etc.). La importación de datos desde cada una de estas fuentes de datos se realiza mediante una función con el prefijo `read_*`. De manera similar, los métodos `to_*` se utilizan para almacenar datos.

####  Google Drive
---

Con ayuda del siguiente código, si trabaja  con google Colab, podrás vincular tu cuenta de Google Drive.

Como recomendación sugerimos tener una carpeta asociada a tu proyecto y dentro de ella otra carpeta denominada `Data` con los archivos que necesites utilizar.

[Carpeta dónde están los dataset](https://drive.google.com/open?id=1bVRLtDii8IpJNOEMT67W3Cwq8yhRxT7r&usp=drive_copy)

Con el siguiente comando podrás abrir el archivo que vamos a necesitar en ésta ocasión, recuerde validar la ruta de Directorio:

In [ ]:
# Importar librería para trabajar con google colab
from google.colab import drive

# Montar drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Configurar para trabajar con las carpetas que alojan los datos y notebook.
import os
# os.chdir() cambia el directorio de trabajo actual a una ruta específica.
os.chdir('/content/drive/MyDrive/cs_ia_2024/POC - curso_on_demand/Contenido para plataforma/CDIA - contenido/Data/') #cambia el directorio de trabajo actual a una ruta específica

#### Importar archivos
---

Para explorar los métodos de Pandas `read_*` vamos a utilizar el conjunto de datos denominados *winemag-data-130k-v2*.

Luego entraremos más en detalle en que consiste este conjunto de datos, por lo pronto, identifiquemos métodos importantes para trabajar con DataFrame.

##### Archivos csv
Utiliza `read_csv()` con la ruta al archivo CSV para leer un archivo de valores separados por comas

In [ ]:
# Importar libreria
import pandas as pd

In [ ]:
# Leer los datos desde archivo csv. Este archivo se encuentra en la carpeta Data
# El argumento por defecto sep = ‘,’, pero si el archivo presenta otro separador , indicar en función
datoscsv_df = pd.read_csv('winemag-data-130k-v2.csv')

# Mostrar los primeros registros del dataframe. Por defecto 5 registros
datoscsv_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Otra opción para evitar columnas

In [ ]:
# Leer los datos desde archivo csv. Este archivo se encuentra en la carpeta Data
# El argumento por defecto sep = ‘,’

datoscsv_df = pd.read_csv('winemag-data-130k-v2.csv', index_col='Unnamed: 0')

# Mostrar los primeros registros del dataframe. Por defecto 5 registros
datoscsv_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Para más información click en [read_csv en documentación oficial](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)

##### Archivos Excel

Leer archivos excel (tanto XLS como XLSX) es tan fácil como la función `read_excel()`, con la ruta del archivo como entrada.

In [ ]:
# Leer los datos desde archivo xlsx. Este archivo se encuentra en la carpeta Data
# Soporta  xls, xlsx, xlsm, xlsb, odf, ods y odt
datosxlsx_df = pd.read_excel('winemag-data-130k-v2.xlsx') # sheet_name='hoja1'

# Mostrar los primeros registros del dataframe. Por defecto 5 registros
datosxlsx_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Leer archivos Excel con varias hojas no es tan diferente. Solo tienes que especificar un argumento adicional, `sheet_name`, en el que puedes pasar una cadena para el nombre de la hoja o un número entero para la posición de la hoja.

Para más información sobre métodos de lectura click en [Funciones de lectura](https://pandas.pydata.org/docs/user_guide/io.html) y  [read_excel en documentación oficial](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)

#### Exportar archivos
---

Pandas te permite exportar datos a varios formatos. Esto ocurre especialmente cuando los datos se transforman mediante pandas y necesitan guardarse localmente en tu máquina. A continuación se explica cómo convertir los DataFrames de pandas a csv y excel.

In [ ]:
# to_csv
# Guardar datoscsv_df como archivo CSV . Controlar la ruta de directorio
# Los argumentos incluyen el nombre del archivo con la ruta y index - donde index = True implica escribir el índice del DataFrame.
datoscsv_df.to_csv("winemag-data-130k-v2_DF.csv", index=False)

In [ ]:
# to_excel() desde el objeto DataFrame para guardarlo como un archivo “.xls” o “.xlsx”.
datosxlsx_df.to_excel("winemag-data-130k-v2_DF.xlsx", index=False)

¿Cómo verificó inicialmentes los datos almacenados en el `DataFrame` ?
---

Continuaremos trabajando con el conjunto de datos `winemag-data-130k-v2.csv`.


* Los datos fueron escrapeados de un sitio determinado(WineEnthusiast) de vino en el año 2017.
* Corresponde a 130.000 reseñas de vinos con características sobre la variedad, ubicación, bodega, precio y descripción del vino.

Para más información click en [Reseña de vino en Kaggle](https://www.kaggle.com/zynicide/wine-reviews/)

**Descripción del conjunto de Datos**
* country: El país de origen del vino.
* description
* designation: El viñedo dentro de la bodega de donde provienen las uvas que hicieron el vino.
* points: La cantidad de puntos que WineEnthusiast calificó al vino en una escala de 1 a 100 (aunque dicen que solo publican reseñas de vinos que puntúan &gt;=80).
* price: El costo de una botella de vino.
* province: La provincia o estado de donde proviene el vino.
* region_1: La zona de cultivo de vino en una provincia o estado (por ejemplo, Napa).
* region_2: A veces, hay regiones más específicas especificadas dentro de una zona de cultivo de vino (por ejemplo, Rutherford dentro del Valle de Napa), pero este valor a veces puede estar en blanco.
* taster_name
* taster_twitter_handle
* title: El título de la reseña del vino.
* variedad: El tipo de uva utilizada para hacer el vino (por ejemplo, Pinot Noir).
* winery: La bodega que elaboró ​​el vino.

In [ ]:
# Leer datos
rev_vino_df = pd.read_csv('winemag-data-130k-v2.csv', index_col='Unnamed: 0')

Para comprobar los datos después de leerlos. Se puede utilizar `head` que muestra de forma predeterminada las primeras 5 filas o `tail` que muestras las últimas 5 filas.

In [ ]:
# Ver 5 primeras filas
rev_vino_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Si quiero ver las primeras 2 filas

In [ ]:
# Primeras 2 filas
rev_vino_df.head(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [ ]:
# Ver 2 últimas filas
rev_vino_df.tail(2)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

Se puede comprobar como Pandas interpretó cada uno de los tipos de datos de la columna solicitando el atributo `dtypes` del objeto :

In [ ]:
rev_vino_df.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

En la sección estadística descriptiva, estaremos explorando los tipos de variables para poder analizar mejor esta información.

Pero en base a los tipos de datos que se cargaron en el Dataframe:
* país, descripción, designación, provincia, región_1, región_2, catador_nombre,
catador_usuario_twitter, título, variedad, bodega son de cadena (objeto).
* puntos y precio son númericos.

Para verificar que estos datos estan correctos, trabajar con la documentación que explique en que consiste cada columna, que luego trataremos como variable.

Para reforzar los tipos de datos en python ver las sección de Fundamentos.

Para obtener un resumen técnico del DataFrame que almacena al conjunto de datos, usar el método `info`

In [ ]:
rev_vino_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

En base a la información compartido por `info`, para el DataFrame:

* Hay 129908 entradas, es decir, 129908 filas.

* Cada fila tiene una etiqueta de fila (también conocida como índice) con valores que van de 0 a 129970.

* La tabla tiene 13 columnas. La mayoría de las columnas tienen un valor para cada una de las filas (los 129970 valores no son nulos). Algunas columnas tienen valores faltantes y menos de 129970 valores no nulos.
  
  * En la sección Datos faltantes profundizaremos en el analisis de está información

* El tipo de datos (objetos, enteros, ...) en las diferentes columnas se resumen enumerando los tipos de datos.

* También se proporciona la cantidad aproximada de RAM utilizada para almacenar el DataFrame.

In [ ]:
# Funcion analisis descriptivo basico base de datos:
def resumen_inicial(datos):
    print("Primeras 5 filas")
    display(datos.head())
    print("-----------------------------------------------------------------")
    print("")

    print("Nombre de columnas")
    display(datos.columns)
    print("-----------------------------------------------------------------")
    print("")

    print("Dimensión")
    display(datos.shape)
    print("-----------------------------------------------------------------")
    print("")

    print("Resumen técnico")
    display(datos.info())
    print("-----------------------------------------------------------------")
    print("")


    print("Datos Faltantes")
    display(datos.isna().sum())
    print("-----------------------------------------------------------------")
    print("")

Existen distintas funciones para explorar el conjunto de datos en el DataFrame. Teniendo en cuenta la función creada `descriptivo`, ordenamos la información que proporcionan diferentes métodos de Pandas.

In [ ]:
resumen_inicial(rev_vino_df)

Primeras 5 filas

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

-----------------------------------------------------------------

Nombre de columnas

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

-----------------------------------------------------------------

Dimensión

(129971, 13)

-----------------------------------------------------------------

Resumen técnico
<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

None

-----------------------------------------------------------------

Datos Faltantes

country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

-----------------------------------------------------------------

### ¿Cómo selecciono un subconjunto de datos de un DataFrame?
---

Deseamos seleccionar los puntos asignados a los vinos (points). Recordemos
points representa laa cantidad de puntos que WineEnthusiast calificó al vino en una escala de 1 a 100 (aunque dicen que solo publican reseñas de vinos que puntúan >=80).

In [ ]:
# Seleccionar características
punto = rev_vino_df["points"]

# Observamos los primeros 5 valores
punto.head()

0    87
1    87
2    87
3    87
4    87
Name: points, dtype: int64

Cada columna de un DataFrame es una serie. Si se selecciona una sola columna, el objeto devuelto es una serie de pandas.

Ahora nos interesa los puntos (points) y el páis (country) de los vinos del conjunto de datos. Recordemo  que country representa el país de origen del vino.

In [ ]:
# Seleccionar valores de pais y punto del conjunto de datos
rev_vino_df[["country","points"]]

         country  points
0          Italy      87
1       Portugal      87
2             US      87
3             US      87
4             US      87
...          ...     ...
129966   Germany      90
129967        US      90
129968    France      90
129969    France      90
129970    France      90

[129971 rows x 2 columns]

La selección devolvió un DataFrame. Para verificarlo, se puede utilizar la función de Pandas `type`

In [ ]:
type(rev_vino_df[["country","points"]])

pandas.core.frame.DataFrame

Vimos que en en Pandas podemos filtrar por máscara.
Seleccionamos todos los vinos con cuyo puntos correspondan al máximo punto del conjunto de datos.

Busco el valor máximo en puntos.

In [ ]:
# Llamar a la función max
rev_vino_df["points"].max()

100

In [ ]:
# Definir la máscara de filtro
max_mascara = rev_vino_df["points"] == rev_vino_df["points"].max()

# Mostrar máscara
max_mascara

0         False
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: points, Length: 129971, dtype: bool


La salida de la expresión condicional (==, pero también  !=, <,>, <=,… funcionaría) es en realidad una serie de valores booleanos de pandas (ya sea Verdadero o Falso) con la misma cantidad de filas que el DataFrame original. Dicha serie de valores booleanos se puede utilizar para filtrar el DataFrame colocándolo entre los corchetes de selección []. Solo se seleccionarán las filas para las que el valor sea Verdadero.

In [ ]:
# Guardar y seleccionar vinos en base a la condición  máscara
maxPun_vino_df = rev_vino_df[max_mascara]

# Mostrar
maxPun_vino_df

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
7335,Italy,Thick as molasses and dark as caramelized brow...,Occhio di Pernice,100,210.0,Tuscany,Vin Santo di Montepulciano,NaN,NaN,NaN,Avignonesi 1995 Occhio di Pernice (Vin Santo ...,Prugnolo Gentile,Avignonesi
36528,France,This is a fabulous wine from the greatest Cham...,Brut,100,259.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Krug 2002 Brut (Champagne),Champagne Blend,Krug
39286,Italy,"A perfect wine from a classic vintage, the 200...",Masseto,100,460.0,Tuscany,Toscana,NaN,NaN,NaN,Tenuta dell'Ornellaia 2007 Masseto Merlot (Tos...,Merlot,Tenuta dell'Ornellaia
42197,Portugal,This is the latest release of what has long be...,Barca-Velha,100,450.0,Douro,NaN,NaN,Roger Voss,@vossroger,Casa Ferreirinha 2008 Barca-Velha Red (Douro),Portuguese Red,Casa Ferreirinha
45781,Italy,"This gorgeous, fragrant wine opens with classi...",Riserva,100,550.0,Tuscany,Brunello di Montalcino,NaN,Kerin O’Keefe,@kerinokeefe,Biondi Santi 2010 Riserva (Brunello di Montal...,Sangiovese,Biondi Santi
45798,US,Tasted in a flight of great and famous Napa wi...,NaN,100,200.0,California,Napa Valley,Napa,NaN,NaN,Cardinale 2006 Cabernet Sauvignon (Napa Valley),Cabernet Sauvignon,Cardinale
58352,France,"This is a magnificently solid wine, initially ...",NaN,100,150.0,Bordeaux,Saint-Julien,NaN,Roger Voss,@vossroger,Château Léoville Barton 2010 Saint-Julien,Bordeaux-style Red Blend,Château Léoville Barton
89728,France,This latest incarnation of the famous brand is...,Cristal Vintage Brut,100,250.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Louis Roederer 2008 Cristal Vintage Brut (Cha...,Champagne Blend,Louis Roederer
89729,France,This new release from a great vintage for Char...,Le Mesnil Blanc de Blancs Brut,100,617.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Salon 2006 Le Mesnil Blanc de Blancs Brut Char...,Chardonnay,Salon
111753,France,"Almost black in color, this stunning wine is g...",NaN,100,1500.0,Bordeaux,Pauillac,NaN,Roger Voss,@vossroger,Château Lafite Rothschild 2010 Pauillac,Bordeaux-style Red Blend,Château Lafite Rothschild
111754,Italy,It takes only a few moments before you appreci...,Cerretalto,100,270.0,Tuscany,Brunello di Montalcino,NaN,NaN,NaN,Casanova di Neri 2007 Cerretalto (Brunello di...,Sangiovese Grosso,Casanova di Neri
111755,France,This is the finest Cheval Blanc for many years...,NaN,100,1500.0,Bordeaux,Saint-Émilion,NaN,Roger Voss,@vossroger,Château Cheval Blanc 2010 Saint-Émilion,Bordeaux-style Red Blend,Château Cheval Blanc
111756,France,"A hugely powerful wine, full of dark, brooding...",NaN,100,359.0,Bordeaux,Saint-Julien,NaN,Roger Voss,@vossroger,Château Léoville Las Cases 2010 Saint-Julien,Bordeaux-style Red Blend,Château Léoville Las Cases
113929,US,In 2005 Charles Smith introduced three high-en...,Royal City,100,80.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Charles Smith 2006 Royal City Syrah (Columbia ...,Syrah,Charles Smith
114972,Portugal,"A powerful and ripe wine, strongly influenced ...",Nacional Vintage,100,650.0,Port,NaN,NaN,Roger Voss,@vossroger,Quinta do Noval 2011 Nacional Vintage (Port),Port,Quinta do Noval
118058,US,This wine dazzles with perfection. Sourced fro...,La Muse,100,450.0,California,Sonoma County,Sonoma,NaN,NaN,Verité 2007 La Muse Red (Sonoma County),Bordeaux-style Red Blend,Verité
122935,France,"Full of ripe fruit, opulent and concentrated, ...",NaN,100,848.0,Bordeaux,Pessac-Léognan,NaN,Roger Voss,@vossroger,Château Haut-Brion 2014 Pessac-Léognan,Bordeaux-style White Blend,Château Haut-Brion
123545,US,Initially a rather subdued Frog; as if it has ...,Bionic Frog,100,80.0,Washington,Walla Walla Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Cayuse 2008 Bionic Frog Syrah (Walla Walla Val...,Syrah,Cayuse

`shape` es un atributo de una serie de pandas y un DataFrame que contiene la cantidad de filas y columnas: (nrows, ncolumns). Una serie de pandas es unidimensional y solo se devuelve la cantidad de filas.

In [ ]:
# Ver forma: cantidad de filas y cantidad de columnas
maxPun_vino_df.shape

(19, 13)


Ahora Seleccionemos todos los vinos cuyo origen de país sean de Argentina y Chile. Sabemos que los valores en 'country' contienen a 'Argentina' y 'Chile'.

In [ ]:
# Guardar y seleccionar los vinos de los paises definidos
pais_vino_df = rev_vino_df[rev_vino_df['country'].isin(['Argentina','Chile'])]

# Mostrar los primeros 5 registros
pais_vino_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
16,Argentina,"Baked plum, molasses, balsamic vinegar and che...",Felix,87,30.0,Other,Cafayate,NaN,Michael Schachner,@wineschach,Felix Lavaque 2010 Felix Malbec (Cafayate),Malbec,Felix Lavaque
17,Argentina,Raw black-cherry aromas are direct and simple ...,Winemaker Selection,87,13.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Gaucho Andino 2011 Winemaker Selection Malbec ...,Malbec,Gaucho Andino
36,Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Estampa 2011 Estate Viognier-Chardonnay (Colch...,Viognier-Chardonnay,Estampa
44,Chile,A berry aroma comes with cola and herb notes. ...,NaN,86,9.0,Maule Valley,NaN,NaN,Michael Schachner,@wineschach,Sundance 2011 Merlot (Maule Valley),Merlot,Sundance
51,Chile,This is much different than Casa Silva's 2009 ...,Gran Reserva,85,22.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Casa Silva 2008 Gran Reserva Petit Verdot (Col...,Petit Verdot,Casa Silva

De manera similar a la expresión condicional, la función condicional `isin` devuelve un valor verdadero para cada fila en la que se encuentran los valores de la lista proporcionada. Para filtrar las filas en función de dicha función, se utiliza la función condicional dentro de los corchetes de selección []. En este caso, la condición dentro de los corchetes de selección `rev_vino_df['country'].isin(['Argentina','Chile'])` comprueba para qué filas la columna country es 'Argentina' o 'Chile'.

Ahora seleccionemos vinos con determinadas características, es decir filas y columnas del conjunto de datos.

Seleccionemos las características de país de origen ('country'), precio('price'), puntos('points') de vinos de Argentina y Chile.

In [ ]:
# Guardar y eeleccionar los vinos de los paises definidos
pais_vino_df = rev_vino_df.loc[ rev_vino_df['country'].isin(['Argentina','Chile']), ['country','price','points']]

# Mostrar los primeros 5 registros
pais_vino_df.head()

      country  price  points
16  Argentina   30.0      87
17  Argentina   13.0      87
36      Chile   15.0      86
44      Chile    9.0      86
51      Chile   22.0      85

In [ ]:
# Ver forma: cantidad de filas y cantidad de columnas
pais_vino_df.shape

(8272, 3)

En este caso, se crea un subconjunto de filas y columnas de una sola vez y ya no basta con utilizar corchetes de selección []. Se requieren los operadores `loc/iloc` antes de los corchetes de selección []. Al utilizar `loc/iloc`, la parte antes de la coma son las filas que desea seleccionar y la parte después de la coma son las columnas que desea seleccionar.

Estamos interesadas en las filas 10 a 25 y las columnas 0 a 3.

In [ ]:
# Seleccionar registros en base a posiciones
rev_vino_df.iloc[10:25, 0:3]

,country,description,designation
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN
12,US,"Slightly reduced, this wine offers a chalky, t...",NaN
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso
14,US,Building on 150 years and six generations of w...,NaN
15,Germany,Zesty orange peels and apple notes abound in t...,Devon
16,Argentina,"Baked plum, molasses, balsamic vinegar and che...",Felix
17,Argentina,Raw black-cherry aromas are direct and simple ...,Winemaker Selection
18,Spain,"Desiccated blackberry, leather, charred wood a...",Vendimia Seleccionada Finca Valdelayegua Singl...
19,US,"Red fruit aromas pervade on the nose, with cig...",NaN
20,US,Ripe aromas of dark berries mingle with ample ...,Vin de Maison
21,US,"A sleek mix of tart berry, stem and herb, alon...",NaN
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno
23,US,This wine from the Geneseo district offers aro...,Signature Selection
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat

Nuevamente, se crea un subconjunto de filas y columnas de una sola vez y ya no es suficiente usar solo corchetes de selección []. Cuando esté interesado específicamente en ciertas filas y/o columnas en función de su posición en la tabla, use el operador `iloc` delante de los corchetes de selección [].

### ¿Cómo crear nuevas columnas derivadas de columnas existentes en DataFrame?

Hasta ahora hemos guardados selecciones de filas o columnas en variables. Por ejemplo la selección de subconjunto de datos en `maxPun_vino_df` o `pais_vino_df`.

Recordemos, que cada columna en un DataFrame es una serie, por lo que podemos llamar a atributos y métodos para generar nuevos valores y almacenarlos como una nueva columna en el DataFrame.
Ahora veremos como crear una nueva columna en el DataFrame que llamaremos `stand_price`.



```
DataFrame['nueva_columna'] = valor
```

In [ ]:
# Crear nueva columna. Guardar valores de precio modificado
rev_vino_df['stand_price'] = (rev_vino_df['price'] - rev_vino_df['price'].mean()) /  rev_vino_df['price'].std()

# Mostrar las 5 primeras filas con las columnas price y stand_price'
rev_vino_df[['price','crosstab']].head()

   price  stand_price
0    NaN          NaN
1   15.0    -0.496399
2   14.0    -0.520776
3   13.0    -0.545153
4   65.0     0.722453

Se desea cambiar el nombre de las columnas de datos del DataFrame se puede usar `rename`.

In [ ]:
# rename tiene el atributo inplace, por defecto es Falso, que da lugar a crear uno nuevo.
# Si es Verdadero, se ignora el valor de la copia, por lo tanto se modifica el Dataframe original
rev_vino_df.rename(
    columns={
        "stand_price": "Standard_price"
    }
)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,Standard_price
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,-0.496399
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,-0.520776
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,-0.545153
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,0.722453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),-0.179498
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,0.966223
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,-0.130744
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,-0.081989
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,-0.350137

La función rename() se puede utilizar tanto para etiquetas de filas como de columnas. Proporcione un diccionario con las claves (los nombres actuales) y los valores (los nombres nuevos) para actualizar los nombres correspondientes.Para más información click en [rename en documentación oficial](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename).

#### Funciones de Dataframe

**Unique**

`unique`devuelve los valores unicos en el orden de aparición. Este NO ordena.  Incluye valores NA (valores faltantes). Por ejemplo si quisieras responder:

a) ¿De que países de origen provienen los vinos? o ¿Qúe valores distintos (únicos) hay en la columna country ?

In [ ]:
rev_vino_df['country'].unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

b) ¿ Cuántos valores distintos hay en la columna country ?

In [ ]:
# len() devuelve la cantidad de elementos de un objeto.
# Cuando el objeto es una cadena, la función len() devuelve la cantidad de caracteres de la cadena.
len(rev_vino_df['country'].unique())

44

In [ ]:
rev_vino_df['country'].nunique() # Cuenta la cantidad de valores observados.  No cuenta valores faltantes.

43

**value_counts**

`value_counts` devuelve una serie que contiene la frecuencia de cada fila distinta en el DataFrame. De manera predeterminada, las filas que contienen valores NA se omiten del resultado. De manera predeterminada, la serie resultante estará en orden descendente, de modo que el primer elemento sea la fila que aparece con mayor frecuencia.
Ante la pregunta:

c) ¿ Con qué frecuencia (cuántas veces) aparece cada uno de los paises ?

In [ ]:
rev_vino_df['country'].value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

In [ ]:
# normalize = True devuelve proporciones en lugar de frecuencias. Valor predeterminado False.
# Multiplicando por 100 obtenemos porcentaje
rev_vino_df['country'].value_counts(normalize=True)*100

country
US                        41.955846
France                    17.006651
Italy                     15.041414
Spain                      5.115158
Portugal                   4.380793
Chile                      3.442436
Argentina                  2.925147
Austria                    2.574899
Australia                  1.792807
Germany                    1.666564
New Zealand                1.092311
South Africa               1.078456
Israel                     0.388737
Greece                     0.358715
Canada                     0.197832
Hungary                    0.112387
Bulgaria                   0.108538
Romania                    0.092373
Uruguay                    0.083906
Turkey                     0.069280
Slovenia                   0.066970
Georgia                    0.066201
England                    0.056963
Croatia                    0.056194
Mexico                     0.053884
Moldova                    0.045417
Brazil                     0.040028
Lebanon                    0.026942
Morocco                    0.021554
Peru                       0.012316
Ukraine                    0.010777
Serbia                     0.009237
Czech Republic             0.009237
Macedonia                  0.009237
Cyprus                     0.008468
India                      0.006928
Switzerland                0.005388
Luxembourg                 0.004619
Bosnia and Herzegovina     0.001540
Armenia                    0.001540
Slovakia                   0.000770
China                      0.000770
Egypt                      0.000770
Name: proportion, dtype: float64

Hay distintas estadísticas disponibles que se pueden aplicar a columnas con datos numéricos. Las operaciones en general excluyen los datos faltantes y funcionan en todas las filas de manera predeterminada. Estaremos profundizando en estadística descriptiva en la sección que tiene su nombre. Pero veremos aquí la media (en inglés, *mean*).


**mean**

`mean` devuelve la media de los valores sobre el eje solicitado. Por defecto el eje `axis = 0` , es decir que por defectos calcula la media de los valores de las filas. Por ejemplo:

In [ ]:
rev_vino_df["price"].mean()

g) ¿ Cuántos vinos tienen un precio por encima de la media ?

In [ ]:
rev_vino_df[rev_vino_df["price"]>rev_vino_df["price"].mean()]

#### Apply
Retomando lo visto, utilizaremos el método `apply` de los dataframes de Pandas, nos permite realizar una acción sobre cada fila o columna (sobre un "axis") del dataset.
Por ejemplo, queremos crear una nueva columna que se llame "description_len" y contenga la cantidad de caracteres que hay en cada fila de la columna "description".

Por ejemplo deseamos crear una columna, que tenga la cantidad de caracteres que tiene la columna description. Para ello consideramos `pandas.Series.str.len`
, que calcula la longitud de cada elemento de la serie/índice. Para más información click en [len en documentación oficial](https://pandas.pydata.org/pandas-docs/version/2.0/reference/api/pandas.Series.str.len.html)

In [ ]:
# Guardar y almacenar la cantidad de caracteres de los valores de 'description'
rev_vino_df['description_length'] = rev_vino_df['description'].str.len()

# Mostrar
rev_vino_df[['description','description_length']].head(2)

                                         description  description_length
0  Aromas include tropical fruit, broom, brimston...                 172
1  This is ripe and fruity, a wine that is smooth...                 227

Hagamos un enfoque distinto


Primero: Definamos una función que cuente los caracteres de un string:

In [ ]:
def count_string_len(cadena):
    return len(cadena)

In [ ]:
# Guardar y almacenar la cantidad de caracteres de los valores de 'description' utilizando apply y count_string_len
rev_vino_df['description_length2'] = rev_vino_df['description'].apply(count_string_len)

In [ ]:
# Mostrar
rev_vino_df[['description','description_length2']].head(2)

                                         description  description_length2
0  Aromas include tropical fruit, broom, brimston...                  172
1  This is ripe and fruity, a wine that is smooth...                  227

In [ ]:
rev_vino_df.iloc[1,]

country                                                           Portugal
description              This is ripe and fruity, a wine that is smooth...
designation                                                       Avidagos
points                                                                  87
price                                                                 15.0
province                                                             Douro
region_1                                                               NaN
region_2                                                               NaN
taster_name                                                     Roger Voss
taster_twitter_handle                                           @vossroger
title                        Quinta dos Avidagos 2011 Avidagos Red (Douro)
variety                                                     Portuguese Red
winery                                                 Quinta dos Avidagos
stand_price                                                      -0.496399
description_length                                                     227
description_length2                                                    227
Name: 1, dtype: object

Para utilizar apply, no hace falta definir una función aparte. También podemos hacerlo directamente utilizando funciónes "lambda":

In [ ]:
# Guardar y almacenar la cantidad de caracteres de los valores de 'description' utilizando apply y lambad
rev_vino_df['description_length3'] = rev_vino_df['description'].apply(lambda x: len(x))

In [ ]:
# Mostrar
rev_vino_df[['description','description_length3']].head(2)

                                         description  description_length3
0  Aromas include tropical fruit, broom, brimston...                  172
1  This is ripe and fruity, a wine that is smooth...                  227

#### ¿Cómo resumir un conjunto de datos de un DataFrame?
Un conjunto de datos se puede agregar y agrupar bajo un determinado criterio ya sea para preprocesar datos, analizar, visualizar, entre otros.
Pandas ofrece varias opciones para resumir datos, entre ellos, `agg`, `groupby`, `pivot_table` y `crosstab`.

La agregación y agrupación de datos son técnicas fundamentales en la limpieza y el preprocesamiento de datos, que cumplen varios propósitos críticos. En primer lugar, permiten resumir grandes conjuntos de datos, transformando datos brutos extensos en resúmenes concisos y significativos que facilitan el análisis y la obtención de información.
Además, la agregación ayuda a gestionar datos faltantes o ruidosos al suavizar las inconsistencias y llenar los vacíos con puntos de datos combinados. Estas técnicas también contribuyen a reducir el volumen de datos, mejorar la eficiencia del procesamiento y crear características valiosas para análisis posteriores o modelos de aprendizaje automático.

##### Agregar

La función `Dataframe.aggregate()` se utiliza para aplicar funciones de agregación en una o más columnas. Algunas de las funciones más utilizadas son las siguientes:
* sum: devuelve la suma de los valores del eje solicitado
* min: devuelve el mínimo de los valores del eje solicitado
* max: devuelve el máximo de los valores del eje solicitado
Podemos aplicar la agregación en un DataFrame, df, como `df.aggregate()` o `df.agg()`.

Estas funciones de agregación solo funcionan con columnas de tipo numérico, pero también se podrían crear funciones de agregación para trabajar con otros tipos de datos. Si se desea aplicar agregación:


```
agregacion = df.agg(func)

```

In [ ]:
# Si quiero seleccionar sola las númericas
# rev_vino_df.select_dtypes(include = 'number') # np.number or 'number'

# Seleccionar variables númericas
numerico_df = rev_vino_df[['points','price']]

# Mostrar
numerico_df. head()

   points  price
0      87    NaN
1      87   15.0
2      87   14.0
3      87   13.0
4      87   65.0

In [ ]:
# Indicar el nombre de la función.
# Por defecto axis = 0 (eje de filas).
# Es decir que se agrega por filas, la función se aplica a los valores de las filas asociados a cada columna.
numerico_df.agg('max')

points     100.0
price     3300.0
dtype: float64

In [ ]:
# Indicar la lista de funciones. Por defecto axis = 0 (eje de filas)
numerico_df.agg(['sum','min','max'])

       points      price
sum  11495563  4278086.0
min        80        4.0
max       100     3300.0

In [ ]:
# Indicar Diccionario para especificar para cada columna. Por defecto axis = 0 (eje de filas)
numerico_df.agg({'points' : ['sum', 'min'], 'price' : ['min', 'max']})

# Si no se aplica ninguna agregación específica a una columna
# Entonces le corresponde un valor NaN (faltante)

         points   price
sum  11495563.0     NaN
min        80.0     4.0
max         NaN  3300.0

In [ ]:
# Indicar axis=1 para que agregue por columna, es decir, por cada fila la suma de los valores cada columna asociado.
numerico_df.agg('sum', axis=1)

0          87.0
1         102.0
2         101.0
3         100.0
4         152.0
          ...
129966    118.0
129967    165.0
129968    120.0
129969    122.0
129970    111.0
Length: 129971, dtype: float64

##### Agrupar
Agrupar datos con pandas usando una clave es una operación común para el análisis de datos.
Para agrupar datos usando una clave, usamos el método `groupby()` de un DataFrame y especificamos la columna que queremos usar como clave para agrupar:

```
agrupado = df.groupby('nombre_columna')
```
Después de agrupar, normalmente se desea realizar alguna agregación. Las funciones de agregación comunes incluyen las siguientes:
* agrupado.sum(): calcula la suma de todas las columnas numéricas
* agrupado.mean(): calcula el promedio (media aritmética)
* agrupado.count(): cuenta la cantidad de valores no nulos
* agrupado.agg(['sum', 'mean', 'count']): aplica varias funciones de agregación a la vez: suma, media y recuento


Veamos ejemplos:

In [ ]:
agrupado_por_country = rev_vino_df.groupby('country')
agrupado_por_country

Vemos que groupby nos devuelve un objeto Pandas.core.groupby.generic.DataFrameGroupBy.

Sobre este objeto, podemos aplicar directamente funciones de agregación como:

In [ ]:
# Aplicar count, para cada grupo de categorias de la columna Country contar los valores no nulos asociados
agrupado_por_country.count().head()

,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,stand_price,description_length,description_length2,description_length3
country,,,,,,,,,,,,,,,,
Argentina,3800,2902,3800,3756,3800,3747,0,3797,3797,3800,3800,3800,3756,3800,3800,3800
Armenia,2,2,2,2,2,0,0,2,2,2,2,2,2,2,2,2
Australia,2329,1640,2329,2294,2329,2327,0,2037,2037,2329,2329,2329,2294,2329,2329,2329
Austria,3345,2825,3345,2799,3345,0,0,3337,3337,3345,3345,3345,2799,3345,3345,3345
Bosnia and Herzegovina,2,1,2,2,2,0,0,2,1,2,2,2,2,2,2,2

In [ ]:
# Aplicar mean. Esto funciona para variables númericas
agrupado_por_country.mean().head()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
# Aplicar mean para variables númericas
agrupado_por_country.mean(numeric_only=True).head()

,points,price,stand_price,description_length,description_length2,description_length3
country,,,,,,
Argentina,86.710263,24.510117,-0.264571,250.601579,250.601579,250.601579
Armenia,87.500000,14.500000,-0.508588,214.500000,214.500000,214.500000
Australia,88.580507,35.437663,0.001811,255.039931,255.039931,255.039931
Austria,90.101345,30.762772,-0.112149,249.613752,249.613752,249.613752
Bosnia and Herzegovina,86.500000,12.500000,-0.557342,216.500000,216.500000,216.500000

In [ ]:
# Para especifica columna
agrupado_por_country['points'].mean().head()

country
Argentina                 86.710263
Armenia                   87.500000
Australia                 88.580507
Austria                   90.101345
Bosnia and Herzegovina    86.500000
Name: points, dtype: float64

También podemos agrupar por múltiples columnas:

In [ ]:
# Agrupar por más de 1 columna
agrupado_por_country_prov = rev_vino_df.groupby(['country', 'province'])

# Aplicar count
agrupado_por_country_prov.mean(numeric_only=True).head()

                               points      price  stand_price  \
country   province
Argentina Mendoza Province  86.826593  25.053317    -0.251329
          Other             86.001866  21.203774    -0.345169
Armenia   Armenia           87.500000  14.500000    -0.508588
Australia Australia Other   85.518367  12.427966    -0.559098
          New South Wales   87.694118  25.623529    -0.237429

                            description_length  description_length2  \
country   province
Argentina Mendoza Province          251.698836           251.698836
          Other                     243.919776           243.919776
Armenia   Armenia                   214.500000           214.500000
Australia Australia Other           215.551020           215.551020
          New South Wales           239.964706           239.964706

                            description_length3
country   province
Argentina Mendoza Province           251.698836
          Other                      243.919776
Armenia   Armenia                    214.500000
Australia Australia Other            215.551020
          New South Wales            239.964706

Y si no queremos que las variables por las que agrupamos se conviertan en indices y sean una columna más, podemos especificarlo en la función:

In [ ]:
# Agrupar por más de 1 columna y modificar el argumento as_index, que por defecto es as_index = True
agrupado_por_country_prov = rev_vino_df.groupby(['country', 'province'], as_index=False)

# Mostrar
agrupado_por_country_prov.mean(numeric_only=True).head()

,country,province,points,price,stand_price,description_length,description_length2,description_length3
0,Argentina,Mendoza Province,86.826593,25.053317,-0.251329,251.698836,251.698836,251.698836
1,Argentina,Other,86.001866,21.203774,-0.345169,243.919776,243.919776,243.919776
2,Armenia,Armenia,87.500000,14.500000,-0.508588,214.500000,214.500000,214.500000
3,Australia,Australia Other,85.518367,12.427966,-0.559098,215.551020,215.551020,215.551020
4,Australia,New South Wales,87.694118,25.623529,-0.237429,239.964706,239.964706,239.964706

Finalmente, también podemos aplicar distintas funciones de agregación a cada columna.


1. Agrupar el conjunto de datos por pais.

2. Obtener una columna que tenga el precio medio por país y otra que contenga la sumatoria de puntos. (`.mean()` y `.sum()` ).

In [ ]:
# Agrupar por pais y agregar de manera determinada para price y points
agrupado_por_country = rev_vino_df.groupby(['country'], as_index=False).agg(
    {'price': ['mean'],
     'points': ['sum']
     })

# Modificar nombre de columna
agrupado_por_country.columns = ["Country",'Price mean', 'Points sum']

# Mostrar
agrupado_por_country.head()

                  Country  Price mean  Points sum
0               Argentina   24.510117      329499
1                 Armenia   14.500000         175
2               Australia   35.437663      206304
3                 Austria   30.762772      301389
4  Bosnia and Herzegovina   12.500000         173

Nota Prácticas recomendadas para agrupar
Al agrupar datos en Pandas, hay varias cosas que se deben tener en cuenta para garantizar resultados precisos:
• Datos faltantes: tenga en cuenta los datos faltantes en las columnas utilizadas para agrupar. Pandas excluirá las filas con datos faltantes del resultado agrupado, lo que puede afectar los cálculos finales.
• MultiIndex: al agrupar por varias columnas, Pandas devuelve un índice jerárquico (MultiIndex). Familiarícese con el trabajo con MultiIndex y considere restablecer el índice si es necesario, como lo hemos estado haciendo para simplificar.
• Orden de operaciones: el orden en el que realiza agrupaciones y agregaciones puede afectar los resultados. Tenga en cuenta la secuencia en la que aplica las funciones de agrupación y agregación.
• Agrupación de conjuntos de datos grandes: para conjuntos de datos grandes, la agrupación puede consumir mucha memoria. Considere usar técnicas como fragmentación o procesamiento paralelo para administrar el uso de memoria y el tiempo de cálculo.

In [ ]:
print("Tabla Ascendente por Points")
display(agrupado_por_country.sort_values(by=['Points sum'], ascending=[True]).head())
print("")
print("--------------------------------")
print("")
print("Tabla Descendente por Points")
display(agrupado_por_country.sort_values(by=['Points sum'], ascending=[False]).head())

Tabla Ascendente por Points

                   Country  Price mean  Points sum
13                   Egypt         NaN          84
34                Slovakia        16.0          87
9                    China        18.0          89
4   Bosnia and Herzegovina        12.5         173
1                  Armenia        14.5         175

--------------------------------

Tabla Descendente por Points

     Country  Price mean  Points sum
40        US   36.573464     4827077
15    France   41.139120     1962855
22     Italy   39.663770     1730506
37     Spain   28.215275      580031
31  Portugal   26.218256      502232

##### Reorganizar

###### Tablas dinámicas (Pivot)
La función `pivot_table()` crea una tabla dinámica de estilo hoja de cálculo como `DataFrame`.
Los niveles de la tabla dinámica se almacenarán en objetos MultiIndex (índices jerárquicos) en el índice y las columnas del `DataFrame`. Se requiere un único valor para cada combinación de índice/columna.



```
pd.pivot_table(data, values, index, columns, aggfunc ...)

```
En términos de sintaxis, el expresion anterior representa lo siguiente:
* data :  un conjunto de datos .
* values : son las columnas a las que se aplicará la función de agregación. Por defecto la función de agregación es mean()
* index : es una columna para agrupar datos. Claves por las que se agruparán en el índice de la tabla dinámica.
* columns: columnas para especificar la categoría de los datos.
* aggfunc es la función de agregación que se aplicará.

Entre otros argumentos.  Para más información click en [pivot table en documentación oficial](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html)

In [ ]:
rev_vino_df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery', 'stand_price', 'description_length',
       'description_length2', 'description_length3'],
      dtype='object')

In [ ]:
pd.pivot_table(rev_vino_df[rev_vino_df['country'].isin(['Argentina','Chile'])], values=['points','price'], index =['variety'], columns=['country'])

                               points                 price
country                     Argentina      Chile  Argentina      Chile
variety
Barbera                     85.000000        NaN  18.000000        NaN
Bonarda                     86.504762        NaN  16.628571        NaN
Bordeaux-style Red Blend    89.820225  90.135135  41.546512  51.513514
Bordeaux-style White Blend  83.000000        NaN  14.000000        NaN
Cabernet Blend              88.250000  88.964286  36.250000  50.321429
...                               ...        ...        ...        ...
Trebbiano                   83.000000        NaN   9.000000        NaN
Trousseau                   88.000000        NaN  60.000000        NaN
Viognier                    84.428571  84.739130  13.380952  13.130435
Viognier-Chardonnay               NaN  84.000000        NaN  14.600000
White Blend                 84.875000  84.370370  20.741935  15.814815

[97 rows x 4 columns]

#### ¿Cómo combinar datos de varias tablas?

En los proyectos de análisis de datos, es habitual encontrar datos distribuidos en múltiples fuentes o conjuntos de datos. Cada conjunto de datos puede contener diferentes piezas de información relacionadas con una entidad o tema común.


##### Concatenación de DataFrames
Cuando tienes conjuntos de datos distribuidos en varios DataFrames con estructuras similares (las mismas columnas o las mismas filas) y quieres combinarlos en un único DataFrame, aquí es donde la concatenación resulta muy útil. El proceso de concatenación puede realizarse a lo largo de un eje en particular, ya sea por filas (eje=0) o por columnas (eje=1).

La función `concat()` se utiliza para concatenar lista de `DataFrames` o lista de `Series`.  Veamos ejemplo:

In [ ]:
# DataFrame 1 con los dos primero registros
df1 = rev_vino_df[['country','price']].head(2)
# Mostrar
display('DF1 ',df1)
print("--------------------------------")
# DataFrame 1 con los dos últimos registros
df2 = rev_vino_df[['country','price','points']].tail(2)
# Mostrar
display('DF2 ',df2)

'DF1 '

    country  price
0     Italy    NaN
1  Portugal   15.0

--------------------------------

'DF2 '

       country  price  points
129969  France   32.0      90
129970  France   21.0      90

In [ ]:
# Concatenar lista de DataFrames. Por defecto axis=0, se concatenan filas, apilando los DataFrames uno sobre el otro.
pd.concat([df1,df2])

         country  price  points
0          Italy    NaN     NaN
1       Portugal   15.0     NaN
129969    France   32.0    90.0
129970    France   21.0    90.0

In [ ]:
# Concatenar por columnas
df1 = rev_vino_df[['country','price']].head(10)
# Mostrar
display('DF1',df1)
print("--------------------------------")
df2 = rev_vino_df[['points','variety']].head(10)
# Mostrar
display('DF2',df2)

'DF1'

    country  price
0     Italy    NaN
1  Portugal   15.0
2        US   14.0
3        US   13.0
4        US   65.0
5     Spain   15.0
6     Italy   16.0
7    France   24.0
8   Germany   12.0
9    France   27.0

--------------------------------

'DF2'

   points             variety
0      87         White Blend
1      87      Portuguese Red
2      87          Pinot Gris
3      87            Riesling
4      87          Pinot Noir
5      87  Tempranillo-Merlot
6      87            Frappato
7      87      Gewürztraminer
8      87      Gewürztraminer
9      87          Pinot Gris

In [ ]:
# Concatenar lista de DataFrames. axis=1, se concatenan columnas, se agregan columnas teniendo en cuenta el indice del Dataframe
pd.concat([df1,df2], axis = 1)

    country  price  points             variety
0     Italy    NaN      87         White Blend
1  Portugal   15.0      87      Portuguese Red
2        US   14.0      87          Pinot Gris
3        US   13.0      87            Riesling
4        US   65.0      87          Pinot Noir
5     Spain   15.0      87  Tempranillo-Merlot
6     Italy   16.0      87            Frappato
7    France   24.0      87      Gewürztraminer
8   Germany   12.0      87      Gewürztraminer
9    France   27.0      87          Pinot Gris

##### Fusión de DataFrames
La función `merge()` admite múltiples opciones de unión similares a las operaciones de estilo de base de datos. Fusiona objetos `DataFrame` o `Serie` con nombre con una unión de estilo base de datos.

https://pandas.pydata.org/docs/reference/api/pandas.merge.html#pandas.merge


Estos son los siguientes tipos de uniones:
* La unión interna toma la intersección de dos o más `DataFrame` o `Serie`. Corresponde a la UNIÓN INTERNA en el lenguaje de consulta estructurado (SQL).
* La ​​unión externa toma la unión de dos o más `DataFrame` o `Serie`. Corresponde a la UNIÓN EXTERNA COMPLETA en SQL.
* La unión izquierda usa solo las claves del `DataFrame` o `Serie` izquierdo. Corresponde a la UNIÓN EXTERNA IZQUIERDA en SQL.
* La unión derecha usa solo las claves del `DataFrame` o `Serie` derecho. Corresponde a la UNIÓN EXTERNA DERECHA en SQL.

In [ ]:

import numpy as np
np.random.seed(1)

# Crear ID en orden
ids = np.arange(1,rev_vino_df.shape[0]+1)

# Crear DF
rev_vino_df['ID'] = ids
df1 = rev_vino_df[['ID','country','price']].head(5)
# Mostrar
display('DF1',df1)
print("--------------------------------")
df2 = rev_vino_df[['ID','points','variety']].head(15)
# Mostrar
display('DF2',df2)

'DF1'

   ID   country  price
0   1     Italy    NaN
1   2  Portugal   15.0
2   3        US   14.0
3   4        US   13.0
4   5        US   65.0

--------------------------------

'DF2'

    ID  points             variety
0    1      87         White Blend
1    2      87      Portuguese Red
2    3      87          Pinot Gris
3    4      87            Riesling
4    5      87          Pinot Noir
5    6      87  Tempranillo-Merlot
6    7      87            Frappato
7    8      87      Gewürztraminer
8    9      87      Gewürztraminer
9   10      87          Pinot Gris
10  11      87  Cabernet Sauvignon
11  12      87      Gewürztraminer
12  13      87  Cabernet Sauvignon
13  14      87   Nerello Mascalese
14  15      87          Chardonnay

In [ ]:
datos_inner_df = pd.merge(df1, df2, on='ID', how='inner')
datos_inner_df

   ID   country  price  points         variety
0   1     Italy    NaN      87     White Blend
1   2  Portugal   15.0      87  Portuguese Red
2   3        US   14.0      87      Pinot Gris
3   4        US   13.0      87        Riesling
4   5        US   65.0      87      Pinot Noir

Como vemos en el fragmento de código anterior, la función `pd.merge()` se utiliza para fusionar los dos DataFrames. El argumento `on='ID'` especifica que la columna ID debe utilizarse como clave para unir los DataFrames. El argumento `how='inner'`especifica que debe realizarse una unión interna. Este tipo de unión devuelve solo las filas que tienen valores coincidentes en ambos DataFrames, que, en este caso, son las filas en las que ID coincide tanto en df1 como en df2.

In [ ]:
datos_outer_df = pd.merge(df1, df2, on='ID', how='outer')
datos_outer_df

    ID   country  price  points             variety
0    1     Italy    NaN      87         White Blend
1    2  Portugal   15.0      87      Portuguese Red
2    3        US   14.0      87          Pinot Gris
3    4        US   13.0      87            Riesling
4    5        US   65.0      87          Pinot Noir
5    6       NaN    NaN      87  Tempranillo-Merlot
6    7       NaN    NaN      87            Frappato
7    8       NaN    NaN      87      Gewürztraminer
8    9       NaN    NaN      87      Gewürztraminer
9   10       NaN    NaN      87          Pinot Gris
10  11       NaN    NaN      87  Cabernet Sauvignon
11  12       NaN    NaN      87      Gewürztraminer
12  13       NaN    NaN      87  Cabernet Sauvignon
13  14       NaN    NaN      87   Nerello Mascalese
14  15       NaN    NaN      87          Chardonnay

Como vemos en el fragmento de código anterior, el argumento `on='ID'` especifica que la columna ID debe utilizarse como clave en la que fusionar los `DataFrames`. El argumento `how='outer'` especifica que debe realizarse una unión externa completa. Este tipo de unión devuelve todas las filas de ambos `DataFrames`, completando NaN donde no hay coincidencia.

In [ ]:
datos_right_df = pd.merge(df1, df2, on='ID', how='right')
datos_right_df

    ID   country  price  points             variety
0    1     Italy    NaN      87         White Blend
1    2  Portugal   15.0      87      Portuguese Red
2    3        US   14.0      87          Pinot Gris
3    4        US   13.0      87            Riesling
4    5        US   65.0      87          Pinot Noir
5    6       NaN    NaN      87  Tempranillo-Merlot
6    7       NaN    NaN      87            Frappato
7    8       NaN    NaN      87      Gewürztraminer
8    9       NaN    NaN      87      Gewürztraminer
9   10       NaN    NaN      87          Pinot Gris
10  11       NaN    NaN      87  Cabernet Sauvignon
11  12       NaN    NaN      87      Gewürztraminer
12  13       NaN    NaN      87  Cabernet Sauvignon
13  14       NaN    NaN      87   Nerello Mascalese
14  15       NaN    NaN      87          Chardonnay

El argumento `how='right'` especifica que se debe realizar una unión externa derecha. Este tipo de unión devuelve todas las filas del DataFrame derecho (df1) y las filas coincidentes del DataFrame izquierdo (df2). Si no hay coincidencia, el resultado tendrá NaN en las columnas del DataFrame izquierdo.

In [ ]:
datos_left_df = pd.merge(df1, df2, on='ID', how='left')
datos_left_df

   ID   country  price  points         variety
0   1     Italy    NaN      87     White Blend
1   2  Portugal   15.0      87  Portuguese Red
2   3        US   14.0      87      Pinot Gris
3   4        US   13.0      87        Riesling
4   5        US   65.0      87      Pinot Noir

El argumento `how='left'` especifica que se debe realizar una unión externa izquierda. Este tipo de unión devuelve todas las filas del DataFrame izquierdo (df2) y las filas coincidentes del DataFrame derecho (df1). Si no hay coincidencias, el resultado tendrá NaN en las columnas del DataFrame derecho.

#### Nota

Manejo de duplicados al fusionar conjuntos de datos
El manejo de claves duplicadas antes de realizar operaciones de fusión es fundamental porque los duplicados pueden generar resultados inesperados, como productos cartesianos, donde las filas se multiplican por la cantidad de entradas coincidentes. Esto no solo puede distorsionar el análisis de datos, sino que también afecta significativamente el rendimiento debido al mayor tamaño del DataFrame resultante.

#### ¿Cómo manejar los datos de series temporales?

Imagina que tienes datos que incluyen información sobre cuándo sucedieron las cosas: poder comprender y manejar esos datos relacionados con el tiempo es clave para dar sentido a los patrones y las tendencias. No se trata solo de comprender cuándo sucedieron las cosas, sino también de facilitar la visualización y el relato de historias con tus datos. Ya sea que estés analizando tendencias a lo largo del tiempo, filtrando datos para períodos específicos o haciendo predicciones con aprendizaje automático, ser bueno con las fechas y las horas es clave para desbloquear información valiosa de los conjuntos de datos que involucran la dimensión del tiempo.
Ahora que entendemos por qué es tan importante manejar las fechas y las horas, el siguiente paso es aprender a captar esa información relacionada con el tiempo y hacer que funcione para nosotros.

In [ ]:
from datetime import datetime
import pandas as pd

In [ ]:
# fecha inicial y final
# https://pandas.pydata.org/docs/reference/api/pandas.date_range.html
fecha_inicial = datetime.strptime("2000-01-01", "%Y-%m-%d")
fecha_final = datetime.strptime("2024-12-31", "%Y-%m-%d")

# Diferencia entre fecha, D representa días
D = 'D'

lista_fechas = pd.date_range(start=fecha_inicial, end= fecha_final, periods = rev_vino_df.shape[0]) #  freq=D
#print(f"Crear lista de fecha desde {fecha_inicial} to {fecha_final}")
print(lista_fechas)

DatetimeIndex([          '2000-01-01 00:00:00',
               '2000-01-01 01:41:10.003847041',
               '2000-01-01 03:22:20.007694083',
               '2000-01-01 05:03:30.011541124',
               '2000-01-01 06:44:40.015388166',
               '2000-01-01 08:25:50.019235208',
               '2000-01-01 10:07:00.023082249',
               '2000-01-01 11:48:10.026929291',
               '2000-01-01 13:29:20.030776333',
               '2000-01-01 15:10:30.034623374',
               ...
               '2024-12-30 08:49:29.965376640',
               '2024-12-30 10:30:39.969223680',
               '2024-12-30 12:11:49.973070720',
               '2024-12-30 13:52:59.976917760',
               '2024-12-30 15:34:09.980764800',
               '2024-12-30 17:15:19.984611840',
               '2024-12-30 18:56:29.988458880',
               '2024-12-30 20:37:39.992305920',
               '2024-12-30 22:18:49.996152960',
                         '2024-12-31 00:00:00'],
              dtype='datetime64[ns]', length=129971, freq=None)

In [ ]:
lista_fechas.dt.days

AttributeError: 'DatetimeIndex' object has no attribute 'dt'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
pathCurso = '/content/drive/MyDrive/CCDAA/Data/'

Con el siguiente comando podrás abrir el archivo que vamos a necesitar en ésta ocasión:

In [ ]:
# Importar Pandas
import Pandas as pd

ruta_archivo = pathCurso + 'certificados-personas-por-fecha-ingreso-provincia-localidad.csv'

In [ ]:
datos = pd.read_csv(ruta_archivo)
datos.head(5)

In [ ]:
datos.info()

In [ ]:
?pd.read_csv

In [ ]:
pd.to_datetime('2023-06-29')

In [ ]:
pd.to_datetime('23-06-29')

In [ ]:
pd.to_datetime('9-6-2023')

In [ ]:
?pd.to_datetime

In [ ]:
pd.to_datetime('9-6-2023',format='%d-%m-%Y')

In [ ]:
datos['fecha_ingreso_2']=pd.to_datetime(datos['fecha_ingreso'])

In [ ]:
datos.info()

In [ ]:
datos.head()

In [ ]:
def funcion(x):
  return pd.to_datetime(x, format='%Y-%m-%d')

In [ ]:
datos2 = pd.read_csv(ruta_archivo,date_parser=funcion)#lambda x: pd.to_datetime(x)
datos2

In [ ]:
datos2.info()

In [ ]:
?pd.read_csv

In [ ]:
datos2 = pd.read_csv(ruta_archivo,parse_dates=['fecha_ingreso'],date_parser=lambda x: pd.to_datetime(x))#lambda x: pd.to_datetime(x)
datos2

In [ ]:
datos2.info()

In [ ]:
datos2 = pd.read_csv(ruta_archivo,date_parser=lambda x: pd.to_datetime(x), index_col="fecha_ingreso")
datos2

In [ ]:
datos2.index

In [ ]:
datos3 = pd.read_csv(ruta_archivo)
datos3['fecha_ingreso'] = pd.to_datetime(datos3['fecha_ingreso'],format='%Y-%m-%d')


# datos3['year'] = pd.DatetimeIndex(datos3['fecha_ingreso']).year
# Otra forma
datos3['year'] = datos3['fecha_ingreso'].dt.year
datos3['month'] = datos3['fecha_ingreso'].dt.month
datos3['day'] = datos3['fecha_ingreso'].dt.day
# datos3['day'] = pd.DatetimeIndex(datos3['fecha_ingreso']).day

In [ ]:
datos3.head(5)

In [ ]:
# Chequeo es una fecha
datos3.info()

¿ Cómo podemos acceder a el día/mes/año de una columna ?

In [ ]:
datos2.head(5)

In [ ]:
#Pero sigamos con datos2
datos2.loc["2020-12-01"].head(5)

In [ ]:
#Pero sigamos con datos3
datos3.loc[datos3["fecha_ingreso"]=="2020-12-01"].head(5)

¿Cómo podemos ver la semana?

In [ ]:
# datos["semana"]=pd.DatetimeIndex(datos['fecha_ingreso']).week
datos3["semana"]=datos3['fecha_ingreso'].dt.isocalendar().week
# El 0 es el lunes

In [ ]:
datos3

## Ejercitación

1) Como ver el día de la semana

In [ ]:
datos3.loc[100]

In [ ]:
datos3["fecha_ingreso"][1].month

In [ ]:
# print(datos3["fecha_ingreso"])
import calendar
calendar.day_name[datos3["fecha_ingreso"][1].weekday()]

In [ ]:
# print(datos3["fecha_ingreso"])
import calendar
calendar.month_name[datos3["fecha_ingreso"][1].month]

2) Imprimir las primeras 5, las útlimas 5 y un sampleo de 5 filas random.

In [ ]:
datos3.head(5)

In [ ]:
datos3.tail(5)

In [ ]:
datos3.sample(5)

3) ¿ Cuántas filas y columnas tiene el dataset ?

In [ ]:
datos3.info()

In [ ]:
datos3.shape

4) ¿ Cuántos valores nulos hay en cada columna ?

In [ ]:
datos3.isna()

In [ ]:
display(datos3.isna().sum())

5) ¿ Qué porcentaje de valores nulos hay en cada columna ?

In [ ]:
display(((datos3.isna().sum())/datos.shape[0])*100)

6) ¿ Cuántos valores distintos encontramos en la variable `destino_provincia` ? ¿Y en `destino_localidad` ?

In [ ]:
datos3.info()

In [ ]:
print(datos3['destino_provincia'].unique())
print(datos3['destino_provincia'].nunique())
print(datos3['fecha_ingreso'].value_counts())

In [ ]:
print(datos3['destino_localidad'].unique())
print(datos3['destino_localidad'].nunique())

7) Convertir los valores de la columna destino_provincia a minúsculas

In [ ]:
#@title Solución
datos3['destino_provincia'] = datos3['destino_provincia'].apply(lambda x: str.lower(x))
# datos3['destino_provincia'] = datos3['destino_provincia'].str.lower()
datos3

8) Calcular la media y mediana de la columna cantidad_personas

In [ ]:
datos3["cantidad_personas"].mean()

In [ ]:
datos3["cantidad_personas"].median()

9) Completar los nulos de la columna cantidad_personas con la mediana y calcular nuevamente la media de la columna. ¿ Cómo varió con respecto a el punto 8) ?

In [ ]:
#@title Solución
mediana = datos3["cantidad_personas"].median()
datos3["cantidad_personas"]= datos3["cantidad_personas"].fillna(mediana)

In [ ]:
media = datos3["cantidad_personas"].mean()
datos3["cantidad_personas"] = datos3["cantidad_personas"].fillna(media)

In [ ]:
datos3["cantidad_personas"].mean()

10) ¿ Cuál es la fecha mínima de ingreso ? ¿ Y la máxima ?

In [ ]:
datos3["fecha_ingreso"].min()

In [ ]:
datos3["fecha_ingreso"].max()

11) ¿ Cuántos certificados se emitieron en Febrero de 2021 ?

In [ ]:
mask_mes_anio = (datos3['month'] == 2) & (datos3['year'] == 2021)
datos3[mask_mes_anio]['cantidad_certificados'].sum()

11.1) ¿Y si quisiera saber los certificados por cada año y mes?

In [ ]:
datos3.groupby(['month']).agg({'cantidad_certificados':["sum"]})

In [ ]:
#@title Solución
datos3.groupby(['year','month'], as_index=False).agg({'cantidad_certificados': ["sum"]})

12) Crear una función que se llame `remove_spaces` que reciba como parámetro un string y retorne el mismo string sin espacios.

In [ ]:
def remove_spaces(string:str) -> str:
    """
    La funcion remueve espacios
    """
    return string.replace(" ", "")

13) Utilizando apply(), aplicar la función `remove_spaces` sobre la columna `destino_localidad` del DataFrame.

In [ ]:
datos3['sin_espacio'] = datos3['destino_localidad'].apply(remove_spaces)

In [ ]:
datos3['sin_espacio'].head(5)

14) Agrupar los datos por `destino_provincia` y obtener:
  - Cantidad total de certificados emitidos
  - Cantidad total de personas que lo solicitaron
  - Fecha de el último certificado emitido

In [ ]:
group_by_destino_provincia = datos3.groupby(['destino_provincia'])

In [ ]:
group_by_destino_provincia['cantidad_certificados','cantidad_personas'].sum()

In [ ]:
fecha_final = datos3.groupby(['destino_provincia'], as_index=False).agg({'fecha_ingreso': ["max"]})
fecha_final.columns = ["Provincia",'Fecha final']
display(fecha_final)

15) ¿ Cuál es la provincia que más certificados emitidos tuvo en Enero de 2021 ?

In [ ]:
mask = (datos3["month"]==1) & (datos3["year"]==2021)

certificados_totales = datos3[mask].groupby(['destino_provincia'], as_index=False).agg({'cantidad_certificados': ["sum"]})
certificados_totales.columns = ["Provincia",'Certificados totales']

display(certificados_totales)

display(certificados_totales.iloc[certificados_totales['Certificados totales'].idxmax()])

## 🎯 Introducción a visualización:

La visualización de datos es una herramienta en CD e IA. Permite comprender mejor los datos, identificar patrones y comunicar hallazgos de manera efectiva. Existe un módulo en donde detallaremos más sobre visualizaciones con datos pero en esta sección exploraremos:
* Los tipos de variables
* Las principales tipos de gráficas
* ¿Cómo crear gráficos con pandas? `

### Tipos de Variables

En estadística las variables, las que se pueden variar, se clasifican en diferentes tipos según la naturaleza de los datos que representan. Aquí un resumen con ejemplos:

**Variables Cualitativas (o Categóricas)**

Son aquellas que representan características o categorías que no pueden ser medidas con números. Se dividen en dos tipos:

* Nominales: No tienen un orden específico.
  * Ejemplo: Color de ojos (azul, verde, marrón), estado civil (soltero, casado, divorciado).
* Ordinales: Tienen un orden o jerarquía, pero las diferencias entre valores no son necesariamente iguales.
  * Ejemplo: Nivel de satisfacción (bajo, medio, alto), nivel educativo (primaria, secundaria, universidad).

**Variables Cuantitativas (o Numéricas)**

Son aquellas que representan cantidades, medidas con número y permiten realizar operaciones matemáticas. Se dividen en dos tipos:

* Discretas: Toman un valor finito de valores. Son valores enteros contables (no pueden tomar valores intermedios).
  * Ejemplo: Número de integrantes en el hogar (0, 1, 2, 3), cantidad de autos en un estacionamiento.
* Continuas: Pueden tomar cualquier valor dentro de un rango númerico, incluyendo decimales.
  * Ejemplo: Altura de una persona (1.75 m), temperatura en grados Celsius (23.5°C).


En visualización, el tipo de variable determina la gráfica adecuada para su representación.

###  Tipos de gráficas  

Existen diversas formas de representar datos de manera visual. Algunas de las más utilizadas son:

* Gráficos de barras: Ideales para comparar valores de variables categóricas.

* Histogramas: Útiles para mostrar la distribución de una variable numérica, es decir cómo se distribuyen los diferentes valores de esa variable a lo largo de las observaciones.

* Diagramas de dispersión (scatter plots): Se emplean para analizar la relación entre dos variables numéricas.

* Gráficos de líneas: Representan tendencias a lo largo del tiempo.

* Boxplots: Muestran la distribución y posibles valores atípicos en un conjunto de datos.

### ¿Cómo crear gráficos con pandas?
Pandas permite representar gráficamente los datos de forma inmediata, utilizando el poder de la libreria Matplotlib, que estaremos explorando en el modulo de visualización.
Una manera sencilla de generar gráficos a partir de DataFrames, es utilizando el método `.plot`. Los métodos .plot.* son aplicables tanto a `Series` como a `DataFrame`.

A continuación, un ejemplo práctico, para ello consideremos el conjunto de datos de reseña de vino, visto en anteriores secciones, pero que corresponden a Argentina:

In [ ]:
# Seleccionar vinos de Argentina
rev_vino_argen_df = rev_vino_df[rev_vino_df['country']=='Argentina']

# Mostrar
rev_vino_argen_df.head(4)

In [ ]:
# Recordar tipo de datos del conjunto de datos del DataFrame
rev_vino_argen_df.dtypes

Una comprobación visual rápida de los datos con `.plot()`

In [ ]:
rev_vino_argen_df.plot()

Con un DataFrame, pandas crea de forma predeterminada un gráfico lineal para cada una de las columnas con datos numéricos.

Además del gráfico de líneas predeterminado al utilizar la función `plot`, hay varias alternativas disponibles para representar gráficamente los datos.

Cambiando el parámetro `kind`, podemos generar otros tipos de gráficos como `line` (líneas), `hist` (histograma), `box`(boxplot) o `scatter` (dispersión). Veamos ejemplos:

In [ ]:
# Explorar la distribución de variable númerica price mediante histograma
rev_vino_argen_df['price'].plot(kind='hist')

In [ ]:
# Explorar la relación de las variables númericas price y points. Usamos la gráfica scatter
# Solo se puede aplicar en DataFrame
rev_vino_argen_df[['price','points']].plot(kind='scatter', x='price', y='points')

In [ ]:
# Calculo la frecuencia de cada categoria de la variable categórica `Province`
# value_counts() devuelve una serie
provincias_s = rev_vino_argen_df['province'].value_counts()

# Mostrar
provincias_s

In [ ]:
# Gráfico de barra
provincias_s.plot(kind="bar")

Para más información sobre `plot`, click en [pandas.plot de documentación oficial](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html#pandas.DataFrame.plot).

### ✍ Recordatorio

* Los métodos `.plot.*` son aplicables tanto a `Series` como a `DataFrames`.

* De manera predeterminada, cada una de las columnas se representa como un elemento diferente (línea, diagrama de caja, etc.).

* Todo gráfico creado por pandas es un objeto Matplotlib.




La visualización de datos es clave en el análisis exploratorio y en la comunicación de resultados en CD e IA.

---
# Estadística Descriptiva
---


* Imagina la siguiente lista de números [1, 2, 3, 4, 5, 6, 7, 7, 9, 10]

* Ejemplo de casos de usos:  calificaciones de los estudiantes en matemáticas, nivel de satisfacción ante un servicio, o gastos mensuales en millones de pesos.

In [ ]:
# Importar librería
import numpy as np
import pandas as pd

# Preparar los datos
data = np.array([1, 2, 3, 4, 5, 6, 7, 7, 9, 10])
print(data)

# Medidas de Tendencia Central

### Media

----

Dados los n números ${\{x_{1},x_{2},\ldots ,x_{n}\}}$ la media aritmética se define como:

\begin{equation}
    \bar {x} = {\frac {1}{n}} \sum _{i=1}^{n}x_{i} ={\frac {x_{1}+x_{2}+\cdots +x_{n}}{n}}
\end{equation}


Por ejemplo, para la muestra 8, 5 y -1, su media es:

\begin{equation}
    \bar {x} ={\frac {8+5+(-1)}{3} = 4}
\end{equation}

In [ ]:
# Calcular estadística con numpy
media = np.mean(data)

# Mostrar resultado
print("Media Numpy:", media)

# Calcular estadística con Pandas
data_df = pd.DataFrame(data)
media = data_df[0].mean()

# Mostrar resultado
print("Media Pandas:", media)

In [ ]:
# Datos en dataframe
data_df

### Mediana

---

La mediana es el valor del "medio" de una lista  **ordenada** de datos (o el valor que separa la primera mitad y la segunda mitad de una distribución).

Para una lista ordenada la mediana es calculada de diferente manera dependiendo de la cantidad de elementos de la misma:

**Impar**:

[1, 2, 3, 5, **7**, 8, 9, 10, 15]

9 elementos

La mediana es el valor de la posición 5 (la posición del “medio”)

Mediana =  7

**Par**:

[-5, -1, 0, **1**, **2**, 3, 8, 20]

8 elementos

La mediana es la **media de los valores en las dos posiciones centrales**

Mediana =  (1+2)/2 = 1.5

In [ ]:
# Recordar la variable data = np.array([1, 2, 3, 4, 5, 6, 7, 7, 9, 10])
# Calcular mediana con numpy
mediana = np.median(data)

# Mostrar resultados
print("Mediana Numpy:", mediana)

# Datos de ejemplo
data_df = pd.DataFrame(data)

# Calcular mediana con pandas
mediana = data_df[0].median()

# Mostrar resultados
print("Mediana Pandas:", mediana)

### Moda

---

La moda es el **valor que aparece con mayor frecuencia** o más veces en la distribución.

Por ejemplo, la moda de [0,1,1,2,2,2,2,3,3,4,4,4,5] es 2.

La moda no es necesariamente única. Puede ocurrir que haya dos valores diferentes que sean los más frecuentes.

In [ ]:
# Importar librerias
import statistics
from scipy import stats


# Recordar la variable data = np.array([1, 2, 3, 4, 5, 6, 7, 7, 9, 10])

# Calcular moda con statistics
moda = statistics.mode(data)

# Mostrar resultados
print("Moda con statistics:", moda)

# Calcular moda con scipy
moda = stats.mode(data)

# Mostrar resultados
print("Moda con scipy:", moda.mode)

In [ ]:
data

In [ ]:
# Multimoda
data2 = np.array([0,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5])
moda = statistics.multimode(data2)

print("Multi Moda Pandas:", moda)

# Medidas de Dispersión o Variabilidad

---

### Varianza

---

La varianza es un valor numérico utilizado para describir cuánto varían los números de una distribución respecto a su media.

Si tenemos un conjunto de valores de una variable, la varianza se calcula de la siguiente forma:

\begin{equation}
\sigma_{n}^{2} = \frac{1}{n} \sum _{i=1}^{n} (x_i - \bar{x})^{2}
\end{equation}

Siendo:

$x_{i}$: cada dato

$\bar{x}$: media de los datos

$n$: número de datos

Esto es el promedio de **la diferencia elevada al cuadrado entre cada valor y la media**

In [ ]:
# Recordar la variable data = np.array([1, 2, 3, 4, 5, 6, 7, 7, 9, 10])

# Calcular varianza con numpy
varianza = np.var(data)

# Mostrar resultados
print("Varianza con numpy:",varianza)

# Calcular varianza con pandas
data_df = pd.DataFrame(data)
varianza = data_df[0].var(ddof=0)

# Mostrar resultados
print("Varianza con pandas:",varianza)

### Desvío Estándar

---

Es la raíz cuadrada de la varianza

\begin{equation}
\sigma_{n} = \sqrt{\frac{1}{n} \sum _{i=1}^{n} (x_i - \bar{x})^{2}}
\end{equation}

El desvío estándar es la raíz cuadrada de la varianza

El desvío es una medida de la dispersión de los datos

**NO** es la desviación promedio con respecto de la media. Como los desvíos están elevados al cuadrado los desvíos muy grandes cuentan más que proporcionalmente.

In [ ]:
# Recordar la variable data = np.array([1, 2, 3, 4, 5, 6, 7, 7, 9, 10])

# Calcular std con numpy
std = np.std(data)

# Mostrar resultados
print("Desvío Estándar con numpy:",std)

# Calcular std con pandas
data_df = pd.DataFrame(data)
std = data_df[0].std(ddof=0)

# Mostrar resultados
print("Desvío Estándar con pandas:",std)

# Medidas de Posición
---
Cuartiles y percentiles son medidas estadísticas que se utilizan para dividir y analizar la distribución de un conjunto de datos. Estas medidas proporcionan información sobre cómo se distribuyen los valores en relación con los demás.

## Cuartiles

Los cuartiles dividen un conjunto de datos en cuatro partes iguales, cada una conteniendo el 25% de los datos. Los cuartiles más comúnmente utilizados son:

* Primer cuartil (Q1): También conocido como el cuartil inferior o el percentil 25 (P25), divide los datos de manera que el 25% de los valores sean menores o iguales a este valor.

* Segundo cuartil (Q2): Es el valor que se encuentra en la mediana, es decir, el punto medio de la distribución. También se conoce como el percentil 50 (P50).

* Tercer cuartil (Q3): También conocido como el cuartil superior o el percentil 75 (P75), divide los datos de manera que el 75% de los valores sean menores o iguales a este valor.

Los cuartiles son útiles para comprender la dispersión y la forma de la distribución de los datos.


![image.png]()

In [ ]:
# Recordar la variable data = np.array([1, 2, 3, 4, 5, 6, 7, 7, 9, 10])

# Calcular los cuartiles con numpy
q1 = np.quantile(data, 0.25)
q2 = np.quantile(data, 0.50)
q3 = np.quantile(data, 0.75)

# Imprimir los cuartiles
print("Primer cuartil (Q1):", q1)
print("Segundo cuartil (Q2):", q2)
print("Tercer cuartil (Q3):", q3)

# Calcular los cuartiles con pandas
data_df = pd.DataFrame({'A':data})

q1 = data_df['A'].quantile(0.25)
q2 = data_df['A'].quantile(0.50)
q3 = data_df['A'].quantile(0.75)

# Imprimir los cuartiles
print("Primer cuartil (Q1):", q1)
print("Segundo cuartil (Q2):", q2)
print("Tercer cuartil (Q3):", q3)
data

## Percentiles

Los percentiles son valores que dividen un conjunto de datos en cien partes iguales, proporcionando una medida más detallada de la distribución. Algunos percentiles comunes son:

* Percentil 25 (P25): Es equivalente al primer cuartil (Q1) y representa el valor por debajo del cual el 25% de los datos caen.

* Percentil 50 (P50): Es equivalente al segundo cuartil (Q2) y representa la mediana de los datos.

* Percentil 75 (P75): Es equivalente al tercer cuartil (Q3) y representa el valor por debajo del cual el 75% de los datos caen.

* Percentil 90 (P90): Representa el valor por debajo del cual el 90% de los datos caen.


Los percentiles proporcionan información más detallada sobre cómo se distribuyen los datos, especialmente en los extremos de la distribución.


![image.png]()

In [ ]:
# Calcular percentiles con NumPy
p25 = np.percentile(data, 25)
p50 = np.percentile(data, 50)
p75 = np.percentile(data, 75)

# Imprimir percentiles con NumPy
print("Percentil 25 (P25):", p25)
print("Percentil 50 (P50):", p50)
print("Percentil 75 (P75):", p75)

# Crear DataFrame de Pandas
data_df = pd.DataFrame({'A':data})

# Calcular percentiles con Pandas
p25_df = data_df['A'].quantile(0.25)
p50_df = data_df['A'].quantile(0.50)
p75_df = data_df['A'].quantile(0.75)

# Imprimir percentiles con Pandas
print("Percentil 25 (P25) con Pandas:", p25_df)
print("Percentil 50 (P50) con Pandas:", p50_df)
print("Percentil 75 (P75) con Pandas:", p75_df)

Tanto los cuartiles como los percentiles son útiles para resumir y analizar grandes conjuntos de datos, y son ampliamente utilizados en campos como la estadística, la investigación social, la economía y muchos otros. Estas medidas permiten comprender mejor la distribución, la dispersión y los valores atípicos de los datos.

# Ejemplo de uso de estadística descriptiva

---

El método describe() del objeto Dataframe devuelve una descripción de los datos en el DataFrame.

Si el DataFrame contiene datos numéricos, la descripción contiene esta información para cada columna:

* count: la cantidad de valores no vacíos.
* mean: el valor promedio (media).
* std: la desviación estándar.
* min: el valor mínimo.
* 25%: el percentil del 25 %*.
* 50%: el percentil del 50 %*.
* 75%: el percentil del 75 %*.
* max: el valor máximo.

In [ ]:
# Describe
data_df.describe()

---
# 1.5 Preparación y preprocesamiento de datos
---

## ✍ ¿Por qué es importante la preparación y preprocesamiento de datos?
La preparación de datos es el proceso que incluye todas las etapas necesarias para transformar datos en bruto en un formato adecuado para su análisis o uso en modelos de aprendizaje de máquina (Machine Learning, ML). Una entrada incorrecta o de mala calidad producirá una salida defectuosa de ellos. **Es muy raro que los datos de los que disponemos estén ya listos para ser usados**.

La preparación de datos es un proceso integral que abarca tareas como la recopilación y combinación de datos provenientes de distintas fuentes, la generación de resúmenes estadísticos y la identificación de problemas en los datos disponibles. Dentro de este proceso se encuentra el preprocesamiento de datos, cuya finalidad es más específica: transformar los datos en un formato óptimo para su uso en modelos de ML y análisis. Este preprocesamiento incluye actividades como la codificación de variables categóricas, la estandarización y normalización de variables numéricas, el manejo de valores atípicos y la imputación de datos faltantes.

Desafíos, que nos estaremos planteando a en está sección.



🛑**Recordemos**

Los datos son la base fundamental para quienes toman decisiones en diversos ámbitos. Por ejemplo, en el sector sanitario, los datos organizados, agregados y transformados pueden proporcionar información valiosa que mejora la atención al paciente, facilita la elaboración de informes con estadísticas fiables y permite monitorear y evaluar los servicios de salud.

## 📝 Temas a explorar
* Codificación de variables categóricas
* Estandarización y Normalización
* Manejo de valores atípicos
* Resumen y caso de uso.

## 💻 Recursos a utilizar
* Conjunto de datos: archivo csv disponible en plataforma. Para más información [archivo csv](https://www.datos.gob.ar/dataset/turismo-certificado-unico-habilitante-para-circulacion-cuhc---verano/archivo/turismo_176dc4bc-7597-4e9b-850d-0d27bcbca8d0).
* Librerías de python: Scikit-learn. Pandas. Numpy. Stats. Matplotlib. Seaborn.
* Jupyter notebook / Google colab.


Comencemos

## 1.5.1 Codificación de variables categóricas

La codificación de variables categóricas es el proceso de transformar datos categóricos (es decir, datos que representan categorías o grupos) en un formato numérico que pueda ser utilizado por los algoritmos de ML. Esto es necesario porque muchos modelos de ML trabajan únicamente con datos numéricos y no pueden interpretar directamente las categorías en texto o etiquetas.

Las variables categóricas son aquellas que toman valores en categorías, como:
* Color de un automóvil (Negro, Blanco, Rojo, Azul, Otros)
* Géneros de libros (Narrativa, Lírica y Dramática)
* Grados académicos (Bachiller, Licenciado, Magíster

Las variables categóricas pueden ser de dos tipos: **nominales y ordinales**. Las nominales no tienen un orden específico, como el  color de un automóvil o géneros de libros. Las ordinales, por otro lado, tienen un orden, como grados académicos en donde el menor grado de estudio es Bachiller y el mayor el Doctorado.

Existen distintas técnicas, aquí exploraremos:

* **Codificación por Etiqueta (Label Encoding)**/**Codificación Ordinal (Ordinal Encoding)**: asigna un número entero a cada categoría de manera arbitraria o en función de su orden o jerarquía.
* **Codificación One-Hot (One-Hot Encoding):** crea una nueva columna binaria para cada categoría y asigna 1 a la categoría presente y 0 a las demás.

![Gráficas asociadas.png]()

Para explorar las tres técnicas utilizaremos el conjunto de datos de grados acádemicos y la libreria scikit-learn de Python.

In [ ]:
# Importar biblioteca para la manipulación de datos
import pandas as pd

# Crear el conjunto de datos sobre grados académicos (Bachiller, Licenciado, Magíster y Doctorado).
# Variable categórica ordinal
educ_ls= ["Bachiller","Bachiller","Bachiller", "Licenciado", "Magíster","Magíster","Doctorado"]
data = {'grado_academico': educ_ls}

# Crear dataframe
educ_df = pd.DataFrame(data)

# Mostrar
display(educ_df)

### Codificación por Etiqueta (Label encoding)

La Codificación por Etiquetas es una técnica que codifica valores categóricos a números enteros. Técnica simple y rápida de implementar aunque puede introducir relaciones numéricas ficticias en variables categóricas nominales como color de un automóvil (Negro, Blanco, Rojo, Azul, Otros) o géneros de libros (Narrativa, Lírica y Dramática).

En Python para realizar la Codificación por Etiquetas se puede usar el módulo `LabelEncoder` de la biblioteca `sklearn.preprocessing`. En donde cada categoría es un entero que comienza en 0 y termina en n-1, donde n es el número de categorías. Veamos esto con el ejemplo.

Empecemos con `LabelEncoder`

In [ ]:
# Importar biblioteca
from sklearn.preprocessing import LabelEncoder

# Inicializar la clase LabelEncoder. Crear instancia
codif_etiqueta = LabelEncoder()

# Entrenar y transformar. LLamar al método fit_transform
educ_df['LABEL_grado_academico_codificada'] = codif_etiqueta.fit_transform(educ_df['grado_academico'])

# Mostrar datos. Se asigna el número por orden alfabético.
# En donde cada categoría es un entero que comienza en 0 y termina en n-1, donde n es el número de categorías
display(educ_df)

In [ ]:
# Si quisieramos ver las valoras asignados a las categorías. classes_
categorias_codificadas = codif_etiqueta.classes_

# Crear un diccionario para almacenar la correspondencia
correspondencia = {}

# Asignar la correspondencia entre las categorías y los números
for i, categoria in enumerate(categorias_codificadas):
    correspondencia[categoria] = i

# Imprimir la correspondencia
print(correspondencia)

La Codificación por Etiquetado no es la mejor técnica. Para el ejemplo, se esperaría desde el grado académico más bajo hasta el más avanzado ('Bachiller'< 'Licenciado'< 'Magíster'<'Doctorado') tener asignado los valores [0,1,2,3] y no [0,2,3,1]. Esto se debe a que asigna por orden alfabético.

Ante este problema, existe la posibilidad de utilizar Codificación Ordinal, útil para variables ordinales.

### Codificación Ordinal (Ordinal Encoding)
Está técnica asignan un valor numérico a cada categoría en función de su orden o jerarquía natural.
En Python, se puede utilizar la clase `OrdinalEncoder` de la biblioteca `sklearn.preprocessing`. Veamos como aplicar al ejemplo de grados académicos:

In [ ]:
# Importar biblioteca
from sklearn.preprocessing import OrdinalEncoder

# Inicializar la clase OrdinalEncoder
codif_ordinal = OrdinalEncoder(categories=[['Bachiller','Licenciado','Magíster','Doctorado']], dtype= 'int') # lista ordenada por nivel de menor a mayor

# Entrenar y transformar
educ_df['ORDINAL_grado_academico_codificada']  = codif_ordinal.fit_transform(educ_df[['grado_academico']]) #

# Mostrar
display(educ_df)

In [ ]:
# Transformando tipo de datos y valores enteros asignados para que comience en 1
educ_df['ORDINAL_grado_academico_codificada'] = educ_df['ORDINAL_grado_academico_codificada'] + 1

# Imprimir los datos originales y los codificados.
# Con Ordinal se logra que el grado académico más bajo sea 'Bachiller'sea 1 y 'Doctorado' sea 4 ('Bachiller'< 'Licenciado'< 'Magíster'<'Doctorado')
display(educ_df)

Algunas características clave de la Codificación Ordinal son:

1. **Asignación de valores numéricos**: A cada categoría única en la variable categórica se le asigna un valor numérico único en función de su orden o jerarquía. Los valores numéricos se asignan de manera secuencial, comenzando desde 0, hasta el número total de categorías menos 1.

2. **Preservación del orden**: La Codificación Ordinal conserva la información de orden o jerarquía entre las categorías. Esto significa que las categorías con valores numéricos más altos representan un mayor orden o jerarquía en comparación con las categorías con valores numéricos más bajos.

3. **Aplicación en variables categóricas ordinales**: La Codificación Ordinal es especialmente útil cuando se trabaja con variables categóricas que tienen un orden lógico predefinido como el ejemplo de grados académicos, clasificaciones (bajo, medio, alto) o tamaños (pequeño, mediano, grande), etc.

### Codificación One-Hot (One-Hot Enconding)

La codificación One-Hot es una técnica utilizada para convertir variables categóricas en una representación numérica binaria. Esta técnica se utiliza cuando las variables categóricas no tienen un orden inherente, variables nominales, y se desea representar cada categoría como una columna binaria separada.

La biblioteca `sklearn.preprocessing` en Python proporciona la clase `OneHotEncoder` que se puede utilizar para realizar la codificación One-Hot. A continuación se muestra un ejemplo de cómo utilizar OneHotEncoder:

In [ ]:
# Importar biblioteca
from sklearn.preprocessing import OneHotEncoder

# Inicializar clase OneHotEncoder
codif_onehot = OneHotEncoder()

# Entrenar y transformar los datos.
columnas_codif  = codif_onehot.fit_transform(educ_df[['grado_academico']])


print("Matriz de columnas:",columnas_codif.toarray())

# Crear dataframes con las nuevas características codificadas One-Hot, y concatenar el DataFrame codificado One-Hot con el DataFrame original:
onehot_df = pd.DataFrame(columnas_codif.toarray(), columns= codif_onehot.get_feature_names_out(['grado_academico']))
educ_onehot_df = pd.concat([educ_df, onehot_df], axis=1)

# Mostrar.
# Aumenta la cantidad de atributos o variables en el conjunto de datos
display(educ_onehot_df)

Está técnica no introduce relaciones ficticias entre categorías aunque aumenta la cantidad de atributos o variables en el conjunto de datos si hay mucha cantidad de categorías asociadas a la variable a codificar.

Para identificar otras técnicas implementadas en scikit-learn click en:
[Documentación  de scikit-learn para codificar características categóricas](https://contrib.scikit-learn.org/category_encoders/)

## 1.5.2 Estandarización y Normalización

La estandarización y la normalización de variables númericas son pasos esenciales del preprocesamiento de datos que ayudan a garantizar que los modelos de ML puedan aprender de los datos de manera eficaz, transforman los valores de las variables a una escala similar, garantizando que todas las variables contribuyan por igual al proceso de aprendizaje del modelo. Por ejemplo, ingresos en miles de dólares y edad en años están en diferentes escalas. Los modelos pueden dar prioridad a los valores más grandes, lo que provoca un sesgo en las predicciones.


Los temas a explorar a continuación son:
* **Estandarización**: Escalado de puntaje Z (Z-score).
* **Normalización**: Escalamiento mínimo-máximo.

### Estandarización

La **estandarización**, también conocida como **normalización z-score**, es una técnica comúnmente utilizada en el preprocesamiento de datos para transformar las variables numéricas de manera que tengan una media de 0 y una desviación estándar de 1. su fórmula está determinada por:

$$Z = \frac{X-\mu}{\sigma}$$

donde $X$ es el valor observado $\mu$ es la media en el conjunto de datos y $\sigma$ es desviación estándar en el conjunto de datos.

![Gráficas asociadas (1).png]()

En Python, se puede utilizar la clase `StandardScaler` de la biblioteca `sklearn.preprocessing` para realizar la estandarización. Para ello planteemos el ejemplo de la edad:

In [ ]:
# Crear dataframe del ejemplo edad
edad_ls =  [18, 20, 22, 21, 19, 23, 18, 24, 40, 41, 45,34, 25, 30, 32, 24, 35, 38, 76, 90]
data = { 'edad': edad_ls }
edad_df = pd.DataFrame(data)

# Imprimir los primeras 5 instancias
edad_df.head(5)

In [ ]:
# Mostrar estadísticas (resumen). Para reforzar estos temas te sugerimos volver a ver los videos de estadísticas descriptiva
# Tiene en cuenta la varianza muestral (n-1)
edad_df.describe()

In [ ]:
# Importar biblioteca
from sklearn.preprocessing import StandardScaler
import numpy as np


# Instanciar la clase StandardScaler
escala_puntoZ = StandardScaler()

# Entrenar y transformar. Nueva variable
edad_df['Z_edad'] = escala_puntoZ.fit_transform(edad_df[['edad']])

# Imprimir primeras 5 instancias.  A cada valor le resto mean	33.750000 y lo dividio por std	18.42 (de la varianza poblacional)
print('Media {} y desvío estándar {} utilizados '. format(escala_puntoZ.mean_[0], np.sqrt(escala_puntoZ.var_)[0]))
edad_df.head(5)

In [ ]:
# Importar biblioteca
import matplotlib.pyplot as plt

# Crear gráfica
fig, axs = plt.subplots(2,1, figsize=(15, 6))
axs[0].hist(edad_df['edad'])
axs[0].set_title("Histograma de 'edad'")
axs[1].hist(edad_df['Z_edad'])
axs[1].set_title("Histograma de 'edad' luego de estandarizar  - Puntaje Z" )
fig.tight_layout()

Los datos no cambian su distribución.

**Cuando usar**

La puntuación z es más adecuada si los datos son numéricos y se distribuyen de manera aproximadamente normal o simétrica. En algoritmos basados en el gradiente como Máquina de Vectores de Soporte (Support Vector Machine, SVM) Regresión lineal o Regresión logística. También en el Análisis de Componentes Principales (Principal Component Analysis, PCA).

### Normalización

La normalización es otro proceso común en el preprocesamiento de datos que se utiliza para escalar los valores de una variable. A diferencia de la estandarización, que centra los datos alrededor de cero y los escala utilizando la desviación estándar, la normalización ajusta los valores en un rango específico, generalmente entre 0 y 1.




#### Escalamiento mínimo-máximo, (Min-Max Scaling)

Existen varios métodos de normalización, pero uno de los más comunes es el Min-Max Scaling. En este enfoque, se transforman los datos a un rango específico utilizando la siguiente fórmula:



$X_{nueva} = \frac{X - X_{min}}{X_{max} - X_{min}}$




donde $X$ es el valor observado, $X_{min}$ es el valor mínimo en el conjunto de datos y $X_{max}$ es el valor máximo en el conjunto de datos. La fórmula normaliza los valores a un rango de [0, 1].

Python ofrece la clase `MinMaxScaler()` de `sklearn.preprocessing`.Veamos como se aplica en el ejemplo edad:

In [ ]:
# Importar biblioteca
from sklearn.preprocessing import MinMaxScaler

# Inicializar la clase MinMaxScaler
escalado_MinMax = MinMaxScaler()

# Entrenar y transformar
edad_df['MINMAX_edad'] = escalado_MinMax.fit_transform(edad_df[['edad']])

# Imprimir las primeras 5 instancias
edad_df.head(5)

In [ ]:
# Crear gráfica
fig, axs = plt.subplots(2,1, figsize=(15, 6))
axs[0].hist(edad_df['edad'])
axs[0].set_title("Histograma de 'edad'")
axs[1].hist(edad_df['MINMAX_edad'])
axs[1].set_title("Histograma de 'edad' luego de normalizar por Mínimo-Máximo " )
fig.tight_layout()


Como se puede ver en la fórmula, el escalado mínimo-máximo conserva el orden relativo de los valores, pero los comprime en un rango específico. El escalamiento Min-Max es ideal cuando los datos no siguen una distribución normal y es importante mantener la relación entre los valores originales. Este método ajusta los datos a un rango específico, como [0, 1], siendo útil en modelos sensibles a magnitudes absolutas, métodos basados en distancias (por ejemplo, k-means o K-Nearest Neighbors). Evite usarlo si los datos contienen valores atípicos, ya que estos pueden comprimir el rango de los valores restantes.

Otras normalizaciones:
* MaxAbsScaler: escala cada variable por su valor absoluto máximo. Rango [-1, 1].
* RobustScaler: resulta particularmente útil cuando se trabaja con conjuntos de datos que contienen valores atípicos.

Todos estos y muchos más están implementados en scikit-learn, click en:[Documentación de preprocesamiento ](https://scikit-learn.org/stable/modules/preprocessing.html)

### 1.5.3 Manejo de valores atípicos (outliers)

La detección y eliminación de valores atípicos es un proceso importante en el preprocesamiento de datos. Definir qué es un valor atípico es una tarea difícil. Un definición de valores atípicos es que son valores que se desvían significativamente de la mayoría de los puntos de datos en un conjunto de datos.

Estos valores atípicos pueden ser causados por errores de medición, anomalías en los datos o eventos raros. La definición de valores atípicos implica reconocer los puntos de datos que no se ajustan al comportamiento esperado de los datos y comprender el contexto en el que ocurren.

Los temas a explorar:
* **Identificación de valores atípicos**: Visualización por Diagrama de caja (Box-plot). Método por Rango Intercuartil (Interquartile Range, IQR). Método por puntuación Z (z-score). Conocimiento de dominio.
* **Eliminación de valores atípicos**.

![Gráficas asociadas (3).png]()

#### Identificación de valores atípicos univariados
Los valores atípicos univariados se producen cuando se observa un valor extremo en una sola variable, independientemente de los valores de otras variables. Se detectan en función de la distribución de una sola variable y, a menudo, se identifican mediante visualizaciones o métodos estadísticos como el puntaje Z o el IQR.
En la siguiente parte, crearemos una de las visualizaciones más comunes para identificar valores atípicos.

Continuamos trabajando con el ejemplo de edad.

#### Visualización por Diagrama de caja (Box-plot)

In [ ]:
# Diagrama de caja
fig, ax = plt.subplots(figsize=(15, 3))
ax.boxplot(edad_df['edad'], vert=False)
ax.set_title("Diagrama de caja (Box Plot) para 'edad'")

![Gráficas asociadas (2).png]()

En un boxplot, los límites del bigote representan los valores mínimo y máximo dentro de un rango aceptable de valores. Estos límites se utilizan para identificar los valores atípicos (outliers) en el conjunto de datos.  
Cualquier valor que esté por encima del límite superior del bigote o por debajo del límite inferior del bigote se considera un valor atípico y se muestra individualmente en el diagrama de caja como un punto o asterisco.

Ahora que hemos visto este gráfico, estamos empezando a formular algunas hipótesis sobre la existencia de valores atípicos específicamente en edad. El siguiente paso es utilizar algunos métodos estadísticos para validar estas
hipótesis, comenzando con el método de IQR, que es esta presente en el Diagrama de caja ya que determina los limites del bigote.

#### Método por Rango Intercuartil (Interquartile Range, IQR)

El IQR es una medida de dispersión estadística que representa el rango entre el tercer cuartil (Q3) y el primer cuartil (Q1) en un conjunto de datos.

Específicamente, este método se aplica calculando la siguiente fórmula:

* Límite inferior del bigote: $Q1 - 1.5 \cdot IQR$
* Límite superior del bigote: $Q3 + 1.5 ⋅ IQR$

donde $IQR$ = rango intercuartil

Recordatorio: cómo calcular el IQR

* Calcular Q1 (percentil 25): Identifica el valor por debajo del cual se encuentra el 25 % de los datos ordenados.
* Calcular Q3 (percentil 75): Identifica el valor por debajo del cual se encuentra el 75 % de los datos ordenados.
* Calcular el IQR: Q3 - Q1.

Es importante señalar que la elección del multiplicador (en este caso, 1.5) es algo arbitrario, pero se ha adoptado ampliamente en la práctica. Ajustar este multiplicador puede hacer que el método sea más o menos sensible a posibles valores atípicos. Por ejemplo, el uso de un multiplicador más grande daría como resultado límites más amplios, lo que podría identificar más puntos de datos como posibles valores atípicos, mientras que un multiplicador más pequeño haría que el método fuera menos sensible.

In [ ]:
# Calcular cuartíles
Q1 = edad_df['edad'].quantile(0.25)
Q3 = edad_df['edad'].quantile(0.75)

# Calcular rango intercualtílico
IQR = Q3 - Q1

# Calcular límites
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Detectar valores atípicos
atipicos_IQR_df = edad_df[(edad_df['edad'] < limite_inferior) | (edad_df['edad'] > limite_superior)]

# Imprimir resultados
print("Atipicos en 'edad' por IQR:")
atipicos_IQR_df['edad']

El método IQR es simple de aplicar, es conveniente en datos no distribuidos normalmente Sin embargo, tiene ciertas desventajas como el tamaño de la muestra, especialmente en conjuntos de datos más pequeños, puede afectar a su precisión a la hora de reflejar la verdadera dispersión de los datos. Detecta atípicos solo en una variable a la vez, lo que puede ser insuficiente si los valores atípicos están en combinaciones de variables (atípicos multivariados).

#### Método de puntuación Z (Z-score)
El método de puntuación Z es una técnica estadística que se utiliza para identificar valores atípicos univariados en un conjunto de datos midiendo en qué medida los puntos de datos individuales se desvían de la media en términos de desviaciones estándar. Recordemos la fórmula de puntuación Z ya vista:


$$Z = \frac{X-\mu}{\sigma}$$

donde $X$ es el valor observado $\mu$ es la media en el conjunto de datos y $\sigma$ es desviación estándar en el conjunto de datos.

Normalmente, se elige una puntuación Z umbral para determinar los valores atípicos. **Los umbrales que se utilizan habitualmente son Z > 3 o Z <− 3, lo que indica que los puntos de datos que se desvían más de tres desviaciones estándar de la media se consideran valores atípicos**.

![Gráficas asociadas NORM.png]()

In [ ]:
# Importar biblioteca
from scipy import stats
from sklearn.preprocessing import StandardScaler
import numpy as np

# Calcular puntajes Z (Z-Scores) usando stats . También se podría utilizar StandardScaler() de sklearn
z_puntaje_edad = np.abs(stats.zscore(edad_df['edad'])) ## para trabajar con valores positivos
edad_df['edad_z_puntaje'] = z_puntaje_edad

# Setear umbral de puntaje z
z_umbral = 3

# Identificar valor atípico
atipicos_estandar_df = edad_df[edad_df['edad_z_puntaje'] >  z_umbral]

# Imprimir resultados
display("Atipicos en 'edad' por puntaje Z :",atipicos_estandar_df['edad'])

Si graficamos las puntuaciones Z para cada observación y característica de los datos, ya podemos empezar a detectar algunos valores atípicos.
En este gráfico de dispersión de puntuaciones Z, cada punto representa la puntuación Z de un punto de datos individual. La línea discontinua roja indica el umbral de puntuación Z elegido (en este caso, 3). Los valores atípicos se identifican como puntos por encima de este umbral.

Continuando con el ejemplo, en edad hay un valor atípico claramente capturado.

In [ ]:
# Crear gráfica
fig, ax = plt.subplots(figsize=(15, 3))
ax.scatter(edad_df['edad_z_puntaje'], edad_df['edad_z_puntaje'], color='blue', label='Z-Scores')
ax.set_title("Puntajes Z (Z-Scores) para 'edad'")
plt.axhline(y=z_umbral, color='red', linestyle='--', label='Umbral')
plt.legend()

La puntuación z es útil para detectar valores atípicos en datos que se distribuyen de forma aproximadamente normal.

**¿Cómo elegir el umbral correcto para la puntuación Z?**

Una puntuación Z le indica a cuántas desviaciones estándar se encuentra un punto de datos con respecto a la media. En una distribución normal, lo siguiente es cierto:
* Aproximadamente el 68 % de los datos se encuentra dentro de una desviación estándar de la media.
* Aproximadamente el 95 % de los datos se encuentra dentro de dos desviaciones estándar
* Aproximadamente el 99,7 % de los datos se encuentra dentro de tres desviaciones estándar.

Esto significa que a menudo se utiliza un umbral de puntuación Z de 3 porque captura valores que están extremadamente alejados
de la media, lo que identifica los valores atípicos más extremos. En una distribución perfectamente normal, solo el 0,3 % de los puntos de datos tendrá una puntuación Z mayor que 3 o menor que -3. Esto lo convierte en un umbral razonable para detectar valores atípicos que es poco probable que formen parte de la distribución normal de datos.

#### Conocimiento del dominio

Para entender mejor el uso del conocimiento del dominio en la detección de valores atípicos, retomemos el ejemplo de la edad.

Supongamos que el conjunto de datos representa la edad de clientes de un banco. En Argentina, se considera adulto una persona de 15 años o más. En base a ejemplo y por reglas del banco, se espera que la edad de una cliente bancario esté entre 15 a 100 años. Se asume que cualquier edad fuera de este rango podría considerarse un valor atípico. Al aprovechar el conocimiento del dominio bancario, podemos establecer estos límites para identificar posibles valores atípicos. Por ejemplo, si la edad de un cliente se registra como 120, probablemente se marcaría como un valor atípico porque excede la edad máxima posible de 100. De manera similar, las edades menores a 15 años. Integrar el conocimiento del dominio de esta manera nos permite establecer umbrales significativos para la detección de valores atípicos, lo que garantiza que el análisis se alinee con las normas esperadas dentro del contexto bancario.

### Eliminación de valores atípicos
La eliminación de valores atípicos se refiere al proceso de remover puntos de datos en un conjunto de datos que se consideran inusualmente extremos o desviados del patrón general de los datos. La eliminación de valores atípicos tiene sus pros y sus contras.
Por un lado, es la forma más sencilla de lidiar con valores extremos. Por otro lado, conduce a una reducción en el tamaño de la muestra y a una posible pérdida de información valiosa. Además, si los valores atípicos no son errores genuinos sino que reflejan una variabilidad legítima en los datos, su eliminación puede introducir sesgo.

Volviendo al ejemplo de edad, vamos a eliminar valores atipicos por Método IQR:

In [ ]:
# Seleccionar edad dentro de los limites
datos_sinAtipicos_IQR_df = edad_df[(edad_df['edad'] >= limite_inferior) & (edad_df['edad'] <= limite_superior)]
display("Estadística para 'edad' con valores atípicos ",edad_df['edad'].describe())
display("Estadística para 'edad' sin valores atípicos por IQR ",datos_sinAtipicos_IQR_df['edad'].describe())

Los cambios observados después de la eliminación de los valores atípicos se describen a continuación:
* **Cambio de la edad media**: la edad media, después de eliminar los valores atípicos, disminuyó ligeramente de 33,75 a
aproximadamente 28,27. Esta reducción sugiere que los valores atípicos eliminados eran individuos mayores.
* **Cambio de la desviación estándar para la edad**: la desviación estándar para la edad disminuyó de 18,90 a 8,75, lo que indica que la dispersión de edades se volvió ligeramente más estrecha después de la eliminación de los valores atípicos, lo que
probablemente contribuyó a una mayor variabilidad en el conjunto de datos original.
*  **Valores mínimos y máximos de edad**: la edad mínima permaneció igual, 18, mientras que la edad máxima disminuyó de 90 a 45, lo que indica que los individuos mayores (posibles valores atípicos) se eliminaron durante el manejo de los valores atípicos.


La eliminación de valores atípicos condujo a una disminución tanto de la edad media como de la desviación estándar, así como a un ligero aumento de la puntuación media de la prueba. Si bien la eliminación de valores atípicos puede mejorar la calidad de los datos, especialmente cuando se deben a errores de entrada de datos o imprecisiones de medición, también reduce la variabilidad del conjunto de datos. Si los valores atípicos representan una variabilidad real en la población, su eliminación podría distorsionar la imagen general de los datos. Para el ejemplo de edad, no estaríamos contemplado a los adultos mayores. Por lo tanto, se debe considerar cuidadosamente si los valores atípicos representan puntos de datos genuinos o errores.


**Impacto de los valores atípicos**

* **Estadísticas de resumen distorsionadas**: los valores atípicos pueden distorsionar significativamente las estadísticas de resumen, dando una impresión errónea de las tendencias centrales de los datos:

  * Media y mediana: la media, una medida común de tendencia central, puede verse muy afectada por los valores atípicos. Un valor atípico con un valor mucho mayor o menor que el resto puede inclinar la media en su dirección. Por otro lado, la mediana está determinada por el valor medio de un conjunto de datos ordenados. Sirve efectivamente como el punto central que divide los datos en dos mitades iguales, haciéndolos menos susceptibles a la influencia de valores extremos.
  * Varianza y desviación estándar: los valores atípicos pueden inflar la varianza y la desviación estándar, haciendo que los datos parezcan más dispersos de lo que realmente están. Esto puede tergiversar la variabilidad de la mayoría de los datos.
* **Visualizaciones engañosas**: los valores atípicos pueden distorsionar la escala y la forma de las visualizaciones, lo que genera una interpretación errónea:
  * Diagramas de caja: los valores atípicos pueden hacer que los diagramas de caja se extiendan excesivamente, lo que hace que la mayor parte de los datos parezcan comprimidos. Esto puede hacer que la distribución parezca menos dispersa de lo que realmente es.
  * Histogramas: los valores atípicos pueden generar la creación de intervalos que capturan solo unos pocos valores extremos, lo que hace que otros intervalos parezcan desproporcionadamente pequeños y que la forma de la distribución esté distorsionada.

* **Influencia en el rendimiento del modelo**: los valores atípicos pueden afectar negativamente el rendimiento de los modelos. por ejemplo modelo de regresión y modelos de clustering.

### Resumen y caso de uso

**1. Codificación de características categóricas**
* Codificación de etiqueta (Label encoding)
* Codificación Ordinal
* Codificación One-Hot (One-Hot encoding)

**2.Estandarización y Normalización**
* Estandarización: escalado de puntaje Z (Z-score)
* Normalización: escalado por mínimo-máximo.

**3.Detección y eliminación de valores atípicos (outliers)**
* Visualización por Diagrama de caja (Box-plot)
* Método por Rango Intercuartil (Interquartile Range, IQR)
* Método por puntuación Z (Z-score)
* Conocimiento de dominio
* Eliminación de valores atípicos por IQR

#### Caso de uso
Para recordar los temas, utilicemos el dataset  `certificados-personas-por-fecha-ingreso-provincia-localidad.csv` que se puede descargar desde este [link](https://www.datos.gob.ar/dataset/turismo-certificado-unico-habilitante-para-circulacion-cuhc---verano/archivo/turismo_176dc4bc-7597-4e9b-850d-0d27bcbca8d0). También disponible en plataforma.

El archivo csv contiene datos de certificados emitidos para circular entre las provincias de Argentina, en época de COVID-19 (2020-2021).

Imaginá, que te solicitan que realizar un análisis y preparar los datos para luego aplicar algún modelo para detectar agrupamiento de compartamientos de movilidad de provincias o localidades.

Te planteas las preguntas: ¿Qué provincias/localidades presentan mayor cantidad de certificados emitidos y personas solicitante? ¿Cómo cambia la relación entre la cantidad de certificados emitidos y personas que lo solicitaron en el tiempo?¿Existe relación entre las provincias o localidades?

**Características del conjunto de datos**
* fecha_ingreso: fecha de registro diario. Tipo de dato Fecha ISO-8601 (date).
* destino_provincia: provincia de destino. Tipo de dato Texto (string).
* destino_localidad:localidad de destino. Tipo de dato Texto (string).   
* cantidad_certificados: cantidad de certificados emitidos. Tipo de dato Número entero (integer).  
* cantidad_personas: cantidad de viajeros o personas que los solicitaron. Tipo de dato Número entero (integer).

In [ ]:
# Configurar para conectarse al drive de google si los datos están alojados allí
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Configurar para trabajar con las carpetas que alojan los datos y notebook. Identificar donde están alojados los datos
import os
# os.chdir() cambia el directorio de trabajo actual a una ruta específica.
os.chdir('./drive/MyDrive/cs_ia_2024/')

In [ ]:
# Validar el directorio en donde están los datos
os.getcwd()

In [ ]:
# Importar bibliotecas
import pandas as pd
import numpy as np

In [ ]:
# Leer Archivo
ruta_archivo =  './data/certificados-personas-por-fecha-ingreso-provincia-localidad.csv'
certif_df = pd.read_csv(ruta_archivo)
# Primeros 5 registros
certif_df.head(5)

In [ ]:
# Identificar estructura del conjunto de datos
certif_df.info(5)

In [ ]:
# Identificar estadística descriptiva
certif_df.describe(include='all')

 Para empezar a responder la pregunta guía **¿Qué provincias/localidades presentan mayor cantidad de certificados emitidos y personas solicitante?**

Se sabe que las provincias presentan diferentes densidades poblacionales y tuvieron diferentes formas de actuar en la pandemía, en algunas de ellas hubo mayores restricciones de circulación.

In [ ]:
# Analizar la variable númerica
certif_df["cantidad_certificados"].hist()

In [ ]:
# Diagrama de caja
fig, ax = plt.subplots(figsize=(12, 3))
ax.boxplot(certif_df["cantidad_certificados"], vert=False)
ax.set_title("Diagrama de caja (Box Plot) para 'cantidad de certificados'")

Se visualiza valores atípicos

In [ ]:
# Cantidad registros por provincia
certif_df["destino_provincia"].value_counts()

Por conocimiento de dominio y pedido, se decide analizar la provincia de Córdoba inicialmente y la cantidad de certificados diarios superior a 20.

In [ ]:
# Seleccionar datos de la provincia de Cordoba
certif_cordoba_df = certif_df[(certif_df["destino_provincia"] == 'Cordoba') & (certif_df["cantidad_certificados"]>20) ]
# Ver estadisticas
certif_cordoba_df.describe(include='all')

In [ ]:
# Diagrama de caja de variable númerica
fig, ax = plt.subplots(figsize=(12, 3))
ax.boxplot(certif_cordoba_df["cantidad_certificados"], vert=False)
ax.set_title("Diagrama de caja (Box Plot) para 'cantidad de certificados' - Córdoba")

In [ ]:
# Método IQR para identificar valores atípicos
# Calcular cuartiles
Q1 = certif_cordoba_df['cantidad_certificados'].quantile(0.25)
Q3 = certif_cordoba_df['cantidad_certificados'].quantile(0.75)
# Calcular rango intercualtílico
IQR = Q3 - Q1

# Calcular limites
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Detectar valores atípicos
atipicos_IQR_df = certif_cordoba_df[(certif_cordoba_df['cantidad_certificados'] < limite_inferior) | (certif_cordoba_df['cantidad_certificados'] > limite_superior)]

# Imprimir resultados
print("Atipicos en 'cantidad de certificados' por IQR:")
atipicos_IQR_df

Hay valores extremos en cantidad de certificados entre las localidades de Córdoba. Se pretende empezar a responder **¿Cómo cambia la relación entre la cantidad de certificados emitidos y personas que lo solicitaron en el tiempo?** antes de remover datos atípicos para identificar otros comportamientos.

In [ ]:
# Convertir dato de fecha a tipo datetime
certif_cordoba_df['fecha_ingreso'] = pd.to_datetime(certif_cordoba_df['fecha_ingreso'])
certif_cordoba_df['fecha_ingreso'].describe()

In [ ]:
# Crear visualización de línea
fig, ax = plt.subplots(figsize=(15, 5))
ax.plot(certif_cordoba_df['fecha_ingreso'],certif_cordoba_df['cantidad_certificados'])
plt.xticks(rotation=90)
plt.show()

Se identifica que hay fechas con comportamiento particular. En cuanto a la pregunta **¿Existe relación entre las localidades?**

Para empezar a responder esta pregunta se codifica la variable 'destino_localidad' y se normaliza por mínimo y máximo para identificar visualmentes relaciones.

In [ ]:
# Importar biblioteca
from sklearn.preprocessing import LabelEncoder

# Inicializar la clase LabelEncoder para codificar la variable destino_localidad
codif_etiqueta = LabelEncoder()

# Entrenar y transformar.Se asigna un número por orden alfabético
certif_cordoba_df['destino_localidad_codificada'] = codif_etiqueta.fit_transform(certif_cordoba_df['destino_localidad'])

# Mostrar datos
certif_cordoba_df

In [ ]:
# Importar biblioteca
from sklearn.preprocessing import MinMaxScaler

# Inicializar la clase MinMaxScaler
escalado_MinMax = MinMaxScaler()

# Entrenar y transformar
certif_cordoba_df['destino_localidad_codificada'] = escalado_MinMax.fit_transform(certif_cordoba_df[['destino_localidad_codificada']])

# Imprimir las primeras 5 instancias
certif_cordoba_df.head(5)

In [ ]:
# Importar biblioteca
import seaborn as sns

g = sns.PairGrid(certif_cordoba_df)
g.map(sns.scatterplot)

En base a la exploración de datos inicial, se observa que hay que definir la estrategía de análisis, ¿por provincias o por localidades?. Se observa valores atípicos. Hay fechas con picos de cantidad de certificados emitidos. Mediante la códificación de la variable 'destino_localidad' no se observa relación lineal aunque podría haber valores atípicos por cantidad de certificados emitidos diariamente. Para trabajar con localidades o provincia sería conveniente utilizar codificación One-Hot por su carácter nominal y ver relaciones.


### Referencia

Zervou, M. (2024). Python Data Cleaning and Preparation Best Practices: A Practical Guide to Organizing and Handling Data from Various Sources and Formats Using Python. (n.p.): Packt Publishing.

Mukhiya, S. K., Ahmed, U. (2020). Hands-On Exploratory Data Analysis with Python: Perform EDA Techniques to Understand, Summarize, and Investigate Your Data. Alemania: Packt Publishing.

McKinney, W. (2012). Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython. Reino Unido: O'Reilly Media.

Hastie, T., Tibshirani, R., Friedman, J. H. (2001). The Elements of Statistical Learning: Data Mining, Inference, and Prediction. Alemania: Springer.